/**
 * BytePrep Template Engine Service
 * Provides 12+ data-driven video & content templates.
 */

import { ShortTemplate } from '../types';

export const CONTENT_TEMPLATES: ShortTemplate[] = [
  {
    id: '10s-challenge',
    name: '10 Second Challenge',
    tagline: 'Fast-paced, high-retention timer countdown challenge',
    badge: '⚡ SPEED CHALLENGE',
    description: 'Hook + 10s urgent circular timer + immediate answer reveal + crisp explanation + Play Store CTA.',
    defaultHook: 'CAN YOU SOLVE THIS IN 10 SECONDS?',
    category: 'challenge',
    introDuration: 4.5,
    hookDuration: 3.0,
    timerDuration: 10.0,
    revealDuration: 4.5,
    explanationDuration: 8.0,
    ctaDuration: 4.0,
    outroDuration: 3.0,
    recommendedTheme: 'byteprep-dark',
    sfxPreset: 'urgent_timer',
  },
  {
    id: 'pyq-challenge',
    name: 'DSSSB / KVS PYQ Exam Trap',
    tagline: 'High-yield past year exam question with trap analysis',
    badge: '🎯 OFFICIAL PYQ',
    description: 'Targeted for CS aspirants with explicit exam year, difficulty rating, and common trap breakdown.',
    defaultHook: 'DSSSB TGT CS EXAM TRAP ⚠️ CAN YOU CRACK IT?',
    category: 'pyq',
    introDuration: 4.0,
    hookDuration: 3.5,
    timerDuration: 10.0,
    revealDuration: 4.5,
    explanationDuration: 9.0,
    ctaDuration: 4.0,
    outroDuration: 3.0,
    recommendedTheme: 'exam-alert',
    sfxPreset: 'pyq_bell',
  },
  {
    id: 'most-students-wrong',
    name: 'Most Students Get This Wrong',
    tagline: 'High-CTR curiosity hook capitalizing on common misconceptions',
    badge: '🤯 95% FAIL RATE',
    description: 'Leverages mistake avoidance and psychological intrigue to drive comments and replay retention.',
    defaultHook: '95% OF CS STUDENTS GET THIS WRONG!',
    category: 'mistake',
    introDuration: 3.5,
    hookDuration: 3.5,
    timerDuration: 10.0,
    revealDuration: 5.0,
    explanationDuration: 9.0,
    ctaDuration: 4.0,
    outroDuration: 3.0,
    recommendedTheme: 'cyber-blue',
    sfxPreset: 'buzzer_reveal',
  },
  {
    id: 'exam-trap',
    name: 'Exam Trap & Negative Marking Warning',
    tagline: 'Reveals the confusing distractor option that causes negative marks',
    badge: '⚠️ NEGATIVE MARKING',
    description: 'Focuses on eliminating confusing distractors and mastering negative marking avoidance.',
    defaultHook: 'DON’T FALL FOR THIS CONFUSING OPTION!',
    category: 'mistake',
    introDuration: 4.0,
    hookDuration: 3.5,
    timerDuration: 10.0,
    revealDuration: 4.5,
    explanationDuration: 8.5,
    ctaDuration: 4.0,
    outroDuration: 3.0,
    recommendedTheme: 'exam-alert',
    sfxPreset: 'warning_chime',
  },
  {
    id: 'concept-challenge',
    name: 'Core Concept in 30 Seconds',
    tagline: 'Deep dive into fundamental algorithms, OS locks, or network protocols',
    badge: '💡 CORE CONCEPT',
    description: 'Educational priority format with rich step-by-step technical breakdown of the underlying theorem.',
    defaultHook: 'MASTER THIS CS CONCEPT BEFORE YOUR EXAM!',
    category: 'concept',
    introDuration: 3.5,
    hookDuration: 3.0,
    timerDuration: 8.0,
    revealDuration: 4.0,
    explanationDuration: 11.0,
    ctaDuration: 4.0,
    outroDuration: 3.0,
    recommendedTheme: 'byteprep-dark',
    sfxPreset: 'clean_tone',
  },
  {
    id: 'quick-cs-fact',
    name: 'Quick CS High-Yield Fact',
    tagline: 'Bite-sized memory booster for direct theoretical exam questions',
    badge: '🧠 CS MEMORY BOOST',
    description: 'Ideal for standard definition & property based questions (OS scheduling, OSI layers, DB keys).',
    defaultHook: 'REMEMBER THIS DIRECT EXAM FACT! 📌',
    category: 'concept',
    introDuration: 3.0,
    hookDuration: 3.0,
    timerDuration: 7.0,
    revealDuration: 4.0,
    explanationDuration: 7.0,
    ctaDuration: 4.0,
    outroDuration: 3.0,
    recommendedTheme: 'cyber-blue',
    sfxPreset: 'ding_quick',
  },
  {
    id: 'guess-before-reveal',
    name: 'Guess Before The Reveal',
    tagline: 'Encourages viewers to pause and leave their option in comments',
    badge: '💬 COMMENT ANSWER',
    description: 'Optimized for high comment engagement by asking viewers to comment A/B/C/D before the timer ends.',
    defaultHook: 'COMMENT YOUR ANSWER BEFORE TIMER HITS 0! ⏱️',
    category: 'challenge',
    introDuration: 3.5,
    hookDuration: 3.0,
    timerDuration: 10.0,
    revealDuration: 5.0,
    explanationDuration: 8.0,
    ctaDuration: 4.0,
    outroDuration: 3.0,
    recommendedTheme: 'byteprep-dark',
    sfxPreset: 'urgent_timer',
  },
  {
    id: 'true-false-breakdown',
    name: 'True/False & Statement Analysis',
    tagline: 'Multi-statement verification questions common in UGC NET & PGT CS',
    badge: '⚖️ STATEMENT CHECK',
    description: 'Structured for multi-statement assertion & reasoning questions.',
    defaultHook: 'IS THIS STATEMENT TRUE OR FALSE?',
    category: 'concept',
    introDuration: 3.5,
    hookDuration: 3.0,
    timerDuration: 10.0,
    revealDuration: 4.5,
    explanationDuration: 9.0,
    ctaDuration: 4.0,
    outroDuration: 3.0,
    recommendedTheme: 'cyber-blue',
    sfxPreset: 'clean_tone',
  },
  {
    id: 'complete-the-code',
    name: 'Complete the Code / Query',
    tagline: 'Python syntax, SQL queries, or C++ pointers quiz format',
    badge: '💻 CODE SNIPPET',
    description: 'Presents syntax or SQL queries with missing keywords or blank slots.',
    defaultHook: 'WHAT WILL COMPLETE THIS CODE / QUERY?',
    category: 'code',
    introDuration: 3.5,
    hookDuration: 3.0,
    timerDuration: 10.0,
    revealDuration: 4.5,
    explanationDuration: 9.0,
    ctaDuration: 4.0,
    outroDuration: 3.0,
    recommendedTheme: 'cyber-blue',
    sfxPreset: 'digital_beep',
  },
  {
    id: 'output-prediction',
    name: 'Output Prediction Challenge',
    tagline: 'Predict the console output of tricky recursion, loops, or pointers',
    badge: '🔍 PREDICT OUTPUT',
    description: 'Evaluates dry-run accuracy for programming questions.',
    defaultHook: 'WHAT WILL BE THE OUTPUT OF THIS CODE?',
    category: 'code',
    introDuration: 3.5,
    hookDuration: 3.0,
    timerDuration: 10.0,
    revealDuration: 4.5,
    explanationDuration: 9.0,
    ctaDuration: 4.0,
    outroDuration: 3.0,
    recommendedTheme: 'byteprep-dark',
    sfxPreset: 'digital_beep',
  },
  {
    id: 'debug-this',
    name: 'Spot the Bug / Debug This',
    tagline: 'Identify runtime errors, logical bugs, or infinite loops',
    badge: '🐛 SPOT THE BUG',
    description: 'Challenges aspirants to spot the faulty line or logical error.',
    defaultHook: 'CAN YOU SPOT THE BUG IN THIS CODE?',
    category: 'code',
    introDuration: 3.5,
    hookDuration: 3.0,
    timerDuration: 10.0,
    revealDuration: 4.5,
    explanationDuration: 9.0,
    ctaDuration: 4.0,
    outroDuration: 3.0,
    recommendedTheme: 'exam-alert',
    sfxPreset: 'warning_chime',
  },
  {
    id: 'rapid-fire',
    name: 'Rapid Fire Speed Round',
    tagline: 'Hyper-quick 5-second blitz question for maximum pace',
    badge: '🔥 RAPID BLITZ',
    description: 'High-energy 5-second blitz test designed for fast Instagram stories and YouTube Shorts loops.',
    defaultHook: 'RAPID FIRE CS BLITZ! 5 SECONDS!',
    category: 'speed',
    introDuration: 2.5,
    hookDuration: 2.5,
    timerDuration: 5.0,
    revealDuration: 3.5,
    explanationDuration: 6.0,
    ctaDuration: 3.0,
    outroDuration: 2.5,
    recommendedTheme: 'exam-alert',
    sfxPreset: 'urgent_timer',
  },
];

export class TemplateService {
  public static getAllTemplates(): ShortTemplate[] {
    return CONTENT_TEMPLATES;
  }

  public static getTemplateById(id: string): ShortTemplate {
    return CONTENT_TEMPLATES.find(t => t.id === id) || CONTENT_TEMPLATES[0];
  }

  public static calculateTotalDuration(template: ShortTemplate, customTimer?: number): number {
    const timer = customTimer !== undefined ? customTimer : template.timerDuration;
    return (
      template.introDuration +
      template.hookDuration +
      timer +
      template.revealDuration +
      template.explanationDuration +
      template.ctaDuration +
      template.outroDuration
    );
  }
}
