// scripts/topics_coa_digital.js
// Topics 1, 7, 8, 9 (80 questions total - 20 per topic)

function q(id, question, options, correctAnswer, explanation, subject, topic, difficulty = 'medium') {
  return { id, question, options, correctAnswer, explanation, subject, topic, difficulty, exam: 'DSSSB TGT CS' };
}

// Topic 1: Computer System Architecture & Organization
const topic1 = [
  q('coa_01', 'In the Von Neumann architecture, which register holds the address of the next instruction to be fetched from memory?',
    ['Instruction Register (IR)', 'Program Counter (PC)', 'Memory Buffer Register (MBR)', 'Accumulator (AC)'], 1,
    'The Program Counter (PC) stores the memory address of the next machine instruction to be executed by the CPU.', 'Computer Architecture', 'Computer System Architecture & Organization', 'easy'),
  q('coa_02', 'Which type of cache mapping allows a memory block to be placed anywhere in the cache?',
    ['Direct Mapping', 'Associative Mapping', 'Set-Associative Mapping', 'Sector Mapping'], 1,
    'In fully associative mapping, any block of main memory can be placed in any cache slot, minimizing conflict misses.', 'Computer Architecture', 'Computer System Architecture & Organization', 'medium'),
  q('coa_03', 'What is the main purpose of the Memory Address Register (MAR)?',
    ['Holds the instruction currently being executed', 'Holds the memory address of data/instruction to be accessed', 'Holds temporary ALU calculation results', 'Holds the status flags of the processor'], 1,
    'MAR (Memory Address Register) holds the address of the memory location currently being read from or written to.', 'Computer Architecture', 'Computer System Architecture & Organization', 'easy'),
  q('coa_04', 'In a 5-stage instruction pipeline (IF, ID, EX, MEM, WB), what hazard occurs when an instruction depends on the result of a previous instruction still in the pipeline?',
    ['Structural Hazard', 'Data Hazard', 'Control Hazard', 'Branch Hazard'], 1,
    'Data hazards (RAW, WAR, WAW) occur when instructions exhibit data dependencies and their operands are not yet available.', 'Computer Architecture', 'Computer System Architecture & Organization', 'medium'),
  q('coa_05', 'Which bus in a computer system is unidirectional?',
    ['Data Bus', 'Control Bus', 'Address Bus', 'System Bus'], 2,
    'The Address Bus is unidirectional; the CPU sends memory or I/O addresses outward to select devices or memory cells.', 'Computer Architecture', 'Computer System Architecture & Organization', 'easy'),
  q('coa_06', 'What technique allows an I/O device to transfer data directly to/from main memory without continuous CPU intervention?',
    ['Programmed I/O', 'Interrupt-driven I/O', 'Direct Memory Access (DMA)', 'Polling'], 2,
    'DMA (Direct Memory Access) allows high-speed peripheral devices to transfer blocks of data directly to memory, freeing the CPU.', 'Computer Architecture', 'Computer System Architecture & Organization', 'easy'),
  q('coa_07', 'In RISC (Reduced Instruction Set Computer) architecture, which characteristic is typically observed?',
    ['Variable instruction length', 'Heavy use of microprogrammed control units', 'Fixed instruction format and single-cycle execution', 'Complex multi-operand memory-to-memory instructions'], 2,
    'RISC processors use fixed-length instructions, load/store architecture, hardwired control, and mostly single-cycle execution.', 'Computer Architecture', 'Computer System Architecture & Organization', 'medium'),
  q('coa_08', 'What is the write policy where data is updated simultaneously in both cache and main memory?',
    ['Write-back', 'Write-through', 'Write-allocate', 'No-write-allocate'], 1,
    'In Write-Through policy, every cache write updates both the cache block and the corresponding main memory location.', 'Computer Architecture', 'Computer System Architecture & Organization', 'easy'),
  q('coa_09', 'Which addressing mode specifies the operand directly within the instruction itself?',
    ['Immediate Addressing', 'Direct Addressing', 'Register Indirect Addressing', 'Indexed Addressing'], 0,
    'In Immediate Addressing Mode, the operand value is part of the instruction itself (e.g., MOV R1, #25).', 'Computer Architecture', 'Computer System Architecture & Organization', 'easy'),
  q('coa_10', 'Booth’s algorithm is specifically designed for which arithmetic operation?',
    ['Division of unsigned numbers', 'Multiplication of signed 2’s complement binary numbers', 'Floating-point normalization', 'BCD addition'], 1,
    'Booth’s multiplication algorithm efficiently multiplies two signed binary numbers in 2’s complement representation.', 'Computer Architecture', 'Computer System Architecture & Organization', 'medium'),
  q('coa_11', 'Which component generates clock signals and control signals to sequence all CPU operations?',
    ['Arithmetic Logic Unit (ALU)', 'Control Unit (CU)', 'Bus Interface Unit', 'Cache Controller'], 1,
    'The Control Unit (CU) coordinates and directs the operations of all processor units by generating timing and control signals.', 'Computer Architecture', 'Computer System Architecture & Organization', 'easy'),
  q('coa_12', 'What is the primary trade-off of a microprogrammed control unit compared to a hardwired control unit?',
    ['Higher speed but higher hardware cost', 'Flexibility and ease of modification at the cost of slower execution speed', 'Inability to execute complex CISC instructions', 'Requires no ROM or memory space'], 1,
    'Microprogrammed control units are flexible and easier to update via microcode, but are slower than hardwired logic.', 'Computer Architecture', 'Computer System Architecture & Organization', 'medium'),
  q('coa_13', 'If a cache hit ratio is 0.9, cache access time is 2 ns, and main memory miss penalty is 50 ns, what is average memory access time?',
    ['5.2 ns', '7.0 ns', '6.8 ns', '52 ns'], 1,
    'Average Access Time = Hit Time + Miss Rate * Miss Penalty = 2 + (0.10 * 50) = 7.0 ns.', 'Computer Architecture', 'Computer System Architecture & Organization', 'hard'),
  q('coa_14', 'What is the function of the Instruction Register (IR)?',
    ['Points to the next memory address', 'Stores the instruction currently being decoded and executed', 'Stores arithmetic carry flag', 'Stores the base address of the stack'], 1,
    'The Instruction Register (IR) holds the binary opcode and operands of the instruction fetched from memory.', 'Computer Architecture', 'Computer System Architecture & Organization', 'easy'),
  q('coa_15', 'In Harvard architecture, what distinguishes it from Von Neumann architecture?',
    ['Separate physical memories and buses for instructions and data', 'Unified memory for instructions and data', 'Absence of ALU', 'Use of only serial data transfer'], 0,
    'Harvard architecture provides physically separate memory storage and signal pathways for instructions and data.', 'Computer Architecture', 'Computer System Architecture & Organization', 'easy'),
  q('coa_16', 'Which interrupt has the highest priority and cannot be ignored by the processor?',
    ['Maskable Interrupt', 'Non-Maskable Interrupt (NMI)', 'Software Interrupt', 'Timer Interrupt'], 1,
    'Non-Maskable Interrupts (NMI) are reserved for critical hardware events (like power failure or parity error) and cannot be masked.', 'Computer Architecture', 'Computer System Architecture & Organization', 'easy'),
  q('coa_17', 'What is the principle of Locality of Reference in memory systems?',
    ['Tendency of processors to access memory uniformly across the entire address space', 'Tendency of processors to access instructions and data close in time or memory location', 'Writing data only to primary storage', 'Using virtual addresses exclusively'], 1,
    'Locality of reference includes temporal locality (recently accessed items accessed again soon) and spatial locality (nearby addresses accessed soon).', 'Computer Architecture', 'Computer System Architecture & Organization', 'easy'),
  q('coa_18', 'Which unit in the CPU performs bitwise AND, OR, and arithmetic additions?',
    ['MMU', 'ALU', 'FPU', 'Control Unit'], 1,
    'The Arithmetic Logic Unit (ALU) performs fundamental arithmetic operations (add, sub) and bitwise logic operations (AND, OR, NOT).', 'Computer Architecture', 'Computer System Architecture & Organization', 'easy'),
  q('coa_19', 'What is pipelining throughput in an ideal k-stage pipeline operating on n tasks?',
    ['Each task completes in k clock cycles always', 'Approximately one task completes per clock cycle after the pipeline fills', 'Requires n*k clock cycles total', 'Cannot overlap instruction phases'], 1,
    'Once an ideal pipeline is filled, one instruction finishes per clock cycle, yielding an ideal speedup of k.', 'Computer Architecture', 'Computer System Architecture & Organization', 'medium'),
  q('coa_20', 'Which register contains the condition codes (Zero flag, Carry flag, Sign flag, Overflow flag)?',
    ['Accumulator', 'Program Status Word (PSW) / Flags Register', 'Instruction Register', 'Base Register'], 1,
    'The Program Status Word (PSW) or Flags register holds status indicators reflecting ALU operation outcomes.', 'Computer Architecture', 'Computer System Architecture & Organization', 'easy'),
];

// Topic 7: Digital Logic & Boolean Algebra
const topic7 = [
  q('dl_01', 'Which logic gate produces a HIGH (1) output only when an odd number of inputs are HIGH (1)?',
    ['AND Gate', 'NAND Gate', 'XOR Gate', 'XNOR Gate'], 2,
    'The Exclusive-OR (XOR) gate outputs 1 if and only if an odd number of its inputs are 1 (parity detector).', 'Digital Electronics', 'Digital Logic & Boolean Algebra', 'easy'),
  q('dl_02', 'According to De Morgan’s theorem, (A + B)’ is equal to:',
    ['A’ + B’', 'A’ · B’', '(A · B)’', 'A + B’'], 1,
    'De Morgan’s first theorem states that the complement of a sum is equal to the product of the complements: (A + B)’ = A’ · B’.', 'Digital Electronics', 'Digital Logic & Boolean Algebra', 'easy'),
  q('dl_03', 'Which of the following gates are known as Universal Gates because any Boolean function can be implemented using only them?',
    ['AND and OR', 'NAND and NOR', 'XOR and XNOR', 'NOT and AND'], 1,
    'NAND and NOR gates are universal gates; any combinational logic circuit can be designed solely with either NAND or NOR gates.', 'Digital Electronics', 'Digital Logic & Boolean Algebra', 'easy'),
  q('dl_04', 'In a 4-variable Karnaugh Map (K-map), how many cells are present?',
    ['8', '16', '32', '64'], 1,
    'A K-map with n variables contains 2^n cells. For 4 variables (e.g., A, B, C, D), there are 2^4 = 16 cells.', 'Digital Electronics', 'Digital Logic & Boolean Algebra', 'easy'),
  q('dl_05', 'Why is Gray code used in labeling adjacent cells of a Karnaugh Map?',
    ['It is an alphanumeric code', 'Adjacent cells differ by only one binary bit', 'It is a weighted binary code', 'It represents negative numbers in 2’s complement'], 1,
    'Gray code is a unit-distance code where adjacent codes differ in only a single bit position, enabling visual grouping of terms.', 'Digital Electronics', 'Digital Logic & Boolean Algebra', 'medium'),
  q('dl_06', 'What is the dual of the Boolean expression: A + B · C = (A + B) · (A + C)?',
    ['A · (B + C) = A · B + A · C', 'A’ · (B’ + C’) = (A’ · B’) + (A’ · C’)', 'A + B + C = A · B · C', 'A · B · C = A + B + C'], 0,
    'The principle of duality swaps AND with OR, and 0 with 1: A + B · C becomes A · (B + C) = A · B + A · C.', 'Digital Electronics', 'Digital Logic & Boolean Algebra', 'medium'),
  q('dl_07', 'In Boolean algebra, what does the consensus theorem state for AB + A’C + BC?',
    ['AB + BC', 'AB + A’C', 'A’C + BC', 'A + B + C'], 1,
    'The consensus theorem states that AB + A’C + BC = AB + A’C. Here, BC is redundant (the consensus term) and can be eliminated.', 'Digital Electronics', 'Digital Logic & Boolean Algebra', 'hard'),
  q('dl_08', 'What is the output of an XNOR gate when both inputs are identical (both 0 or both 1)?',
    ['0', '1', 'High Impedance (Z)', 'Undefined'], 1,
    'An XNOR gate is an equivalence gate; it outputs 1 when both inputs have the same logic level (0,0 or 1,1).', 'Digital Electronics', 'Digital Logic & Boolean Algebra', 'easy'),
  q('dl_09', 'A group of 8 adjacent 1s (an octet) in a 4-variable K-map eliminates how many variables?',
    ['1 variable', '2 variables', '3 variables', '4 variables'], 2,
    'Each grouping of 2^k cells in a K-map eliminates k variables. An octet has 2^3 = 8 cells, eliminating 3 variables.', 'Digital Electronics', 'Digital Logic & Boolean Algebra', 'medium'),
  q('dl_10', 'What are "Don’t Care" conditions (marked as X or d) in a Karnaugh Map?',
    ['Input combinations that must always produce a 0 output', 'Input combinations that never occur or whose outputs do not matter', 'Faulty hardware states', 'Signals with floating voltages'], 1,
    'Don’t Care conditions represent unused input states; they can be treated as 1 or 0 to form larger groups and simplify the circuit.', 'Digital Electronics', 'Digital Logic & Boolean Algebra', 'easy'),
  q('dl_11', 'Simplify the Boolean expression: F = A + A’B.',
    ['A', 'B', 'A + B', 'A · B'], 2,
    'By distributive law: A + A’B = (A + A’)(A + B) = 1 · (A + B) = A + B.', 'Digital Electronics', 'Digital Logic & Boolean Algebra', 'easy'),
  q('dl_12', 'How many 2-input NAND gates are required to implement a 2-input XOR gate?',
    ['3', '4', '5', '6'], 1,
    'A 2-input XOR gate can be synthesized using exactly 4 NAND gates.', 'Digital Electronics', 'Digital Logic & Boolean Algebra', 'medium'),
  q('dl_13', 'Which law states that A · (B · C) = (A · B) · C and A + (B + C) = (A + B) + C?',
    ['Commutative Law', 'Associative Law', 'Distributive Law', 'Absorption Law'], 1,
    'The Associative Law allows grouping of terms in consecutive AND or OR operations without changing the result.', 'Digital Electronics', 'Digital Logic & Boolean Algebra', 'easy'),
  q('dl_14', 'In Sum-of-Products (SOP) form, what is a minterm?',
    ['A sum term containing all variables in either complemented or uncomplemented form', 'A product term containing all variables in either complemented or uncomplemented form', 'Any sum of literals', 'A term with don’t care conditions'], 1,
    'A minterm (canonical product term) is an AND combination of all system variables in true or complemented form.', 'Digital Electronics', 'Digital Logic & Boolean Algebra', 'easy'),
  q('dl_15', 'What is the canonical Product-of-Sums (POS) representation designation for terms?',
    ['Minterms (m)', 'Maxterms (M)', 'Prime Implicants (PI)', 'Essential Prime Implicants (EPI)'], 1,
    'In POS form, canonical sum terms are called Maxterms, designated by M_i.', 'Digital Electronics', 'Digital Logic & Boolean Algebra', 'easy'),
  q('dl_16', 'A Boolean function has an Essential Prime Implicant (EPI) if:',
    ['It contains all minterms', 'It is the largest possible group in the K-map', 'It covers at least one minterm that is not covered by any other prime implicant', 'It contains only don’t care cells'], 2,
    'An Essential Prime Implicant covers at least one 1-cell that cannot be grouped into any other prime implicant.', 'Digital Electronics', 'Digital Logic & Boolean Algebra', 'medium'),
  q('dl_17', 'What is the complement of the function F(A, B) = A · B + A’ · B’?',
    ['A ⊕ B', 'A ⊙ B', 'A + B', 'A’ + B’'], 0,
    'F is the XNOR function (A ⊙ B). The complement of XNOR is the XOR function: (A ⊙ B)’ = A ⊕ B.', 'Digital Electronics', 'Digital Logic & Boolean Algebra', 'medium'),
  q('dl_18', 'What is the value of Boolean expression A · (A + B)?',
    ['B', 'A', 'A · B', 'A + B'], 1,
    'By the Absorption Law of Boolean algebra: A · (A + B) = A · A + A · B = A + A · B = A · (1 + B) = A.', 'Digital Electronics', 'Digital Logic & Boolean Algebra', 'easy'),
  q('dl_19', 'How many 2-input NOR gates are required to implement a 2-input AND gate?',
    ['2', '3', '4', '5'], 1,
    'By De Morgan’s laws: A · B = ((A · B)’)’ = (A’ + B’)’. Inverting A requires 1 NOR, inverting B requires 1 NOR, and NORing A’ and B’ requires 1 NOR = 3 NOR gates.', 'Digital Electronics', 'Digital Logic & Boolean Algebra', 'medium'),
  q('dl_20', 'Which logic gate is equivalent to a negative-AND gate (AND gate with inverted inputs)?',
    ['NAND Gate', 'NOR Gate', 'XOR Gate', 'OR Gate'], 1,
    'By De Morgan’s theorem: A’ · B’ = (A + B)’, which is the operation of a NOR gate.', 'Digital Electronics', 'Digital Logic & Boolean Algebra', 'easy'),
];

// Topic 8: Combinational & Sequential Circuits
const topic8 = [
  q('circ_01', 'A Half Adder circuit can add how many binary bits at a time?',
    ['Three 1-bit binary inputs', 'Two 1-bit binary inputs', 'Four binary bits', 'One 8-bit byte'], 1,
    'A Half Adder adds two 1-bit binary inputs (A and B) and produces two outputs: Sum (A ⊕ B) and Carry (A · B).', 'Digital Electronics', 'Combinational & Sequential Circuits', 'easy'),
  q('circ_02', 'How many select lines are required for a 16-to-1 Multiplexer (MUX)?',
    ['2', '3', '4', '8'], 2,
    'For a 2^n to 1 multiplexer, n select lines are required. For 16-to-1: 16 = 2^4, so 4 select lines are needed.', 'Digital Electronics', 'Combinational & Sequential Circuits', 'easy'),
  q('circ_03', 'What is the main difference between combinational logic and sequential logic circuits?',
    ['Combinational circuits use clock pulses; sequential circuits do not', 'Sequential circuits have memory elements (feedback) whose outputs depend on past inputs', 'Combinational circuits are made only of flip-flops', 'Sequential circuits cannot use NAND gates'], 1,
    'Sequential circuits contain storage elements (latches/flip-flops) and feedback loops, so output depends on present inputs and past history.', 'Digital Electronics', 'Combinational & Sequential Circuits', 'easy'),
  q('circ_04', 'In an SR flip-flop using NOR gates, which input condition is invalid / forbidden?',
    ['S = 0, R = 0', 'S = 0, R = 1', 'S = 1, R = 0', 'S = 1, R = 1'], 3,
    'When S = 1 and R = 1 simultaneously, both outputs Q and Q’ try to become 0, leading to a race condition / forbidden state.', 'Digital Electronics', 'Combinational & Sequential Circuits', 'easy'),
  q('circ_05', 'What problem in an SR flip-flop is resolved by a JK flip-flop?',
    ['Slow propagation delay', 'Invalid state when both inputs are HIGH', 'Lack of set capability', 'High power consumption'], 1,
    'A JK flip-flop resolves the S=1, R=1 ambiguity by causing the output to toggle when J = 1 and K = 1.', 'Digital Electronics', 'Combinational & Sequential Circuits', 'easy'),
  q('circ_06', 'What condition causes Race-Around in a level-triggered JK flip-flop?',
    ['J = 0, K = 0 with clock pulse width smaller than propagation delay', 'J = 1, K = 1 when clock pulse width (tp) is greater than flip-flop propagation delay (Δt)', 'J = 1, K = 0 with inverted clock', 'Clock frequency is zero'], 1,
    'When J=1, K=1 and clock width tp > Δt, the output toggles repeatedly during a single clock pulse, producing an unpredictable state.', 'Digital Electronics', 'Combinational & Sequential Circuits', 'medium'),
  q('circ_07', 'How is the Race-Around condition eliminated in flip-flop design?',
    ['Using Master-Slave JK flip-flop or edge-triggering', 'Increasing the clock pulse duration', 'Removing the feedback loop', 'Using only OR gates'], 0,
    'Race-around is resolved by using edge-triggered flip-flops or a Master-Slave configuration where changes occur strictly at clock transitions.', 'Digital Electronics', 'Combinational & Sequential Circuits', 'medium'),
  q('circ_08', 'Which flip-flop has only one input and reproduces its input at the output after a clock transition?',
    ['T Flip-Flop', 'D Flip-Flop (Delay Flip-Flop)', 'SR Flip-Flop', 'JK Flip-Flop'], 1,
    'A D (Data / Delay) flip-flop passes the input D to output Q on the clock active edge: Q(next) = D.', 'Digital Electronics', 'Combinational & Sequential Circuits', 'easy'),
  q('circ_09', 'A 4-bit synchronous binary counter has a MOD number (modulus) of:',
    ['4', '8', '16', '32'], 2,
    'An n-bit binary counter has 2^n unique counting states (from 0 to 2^n - 1). For 4 bits, MOD = 2^4 = 16.', 'Digital Electronics', 'Combinational & Sequential Circuits', 'easy'),
  q('circ_10', 'A Johnson counter (twisted ring counter) constructed with 4 flip-flops has how many distinct states?',
    ['4', '8', '16', '32'], 1,
    'An n-stage Johnson counter has 2n distinct states. For 4 flip-flops, the number of states is 2 * 4 = 8.', 'Digital Electronics', 'Combinational & Sequential Circuits', 'medium'),
  q('circ_11', 'A standard Ring counter constructed with 5 flip-flops has how many distinct states?',
    ['5', '10', '25', '32'], 0,
    'An n-stage standard ring counter circulates a single 1 through n flip-flops, having exactly n distinct states (here, 5).', 'Digital Electronics', 'Combinational & Sequential Circuits', 'medium'),
  q('circ_12', 'What is the function of a Demultiplexer (DEMUX)?',
    ['Converts multiple inputs into a single output', 'Takes a single input data line and routes it to one of 2^n output lines', 'Adds two binary numbers', 'Stores multi-bit data'], 1,
    'A Demultiplexer takes a single input data line and directs it to one of many destination outputs based on select line values.', 'Digital Electronics', 'Combinational & Sequential Circuits', 'easy'),
  q('circ_13', 'How many Full Adders and Half Adders are required to construct a 4-bit parallel binary adder?',
    ['4 Full Adders (or 3 Full Adders and 1 Half Adder)', '2 Full Adders and 2 Half Adders', '4 Half Adders only', '1 Full Adder and 3 Half Adders'], 0,
    'A 4-bit ripple carry adder can be built using 1 Half Adder (for LSB if no carry-in) and 3 Full Adders, or 4 Full Adders.', 'Digital Electronics', 'Combinational & Sequential Circuits', 'medium'),
  q('circ_14', 'What circuit converts a 3-bit binary code into one of 8 active output lines?',
    ['3-to-8 Decoder', '8-to-3 Priority Encoder', '3-to-1 Multiplexer', 'Binary Comparator'], 0,
    'A 3-to-8 line decoder decodes 3 binary input lines into 2^3 = 8 mutually exclusive output lines.', 'Digital Electronics', 'Combinational & Sequential Circuits', 'easy'),
  q('circ_15', 'What is a Priority Encoder?',
    ['An encoder that gives output only when all inputs are 1', 'An encoder that produces the code corresponding to the highest-order active input', 'A circuit that counts clock cycles in priority order', 'An adder with priority carry'], 1,
    'In a priority encoder, if two or more inputs arrive simultaneously, the input with the highest designated priority takes precedence.', 'Digital Electronics', 'Combinational & Sequential Circuits', 'medium'),
  q('circ_16', 'In a T flip-flop, what is the next state Q(next) when T = 1?',
    ['0', '1', 'Q’ (toggle previous state)', 'No change'], 2,
    'The characteristic equation of a T flip-flop is Q(next) = T ⊕ Q. When T = 1, Q(next) = Q’ (it toggles).', 'Digital Electronics', 'Combinational & Sequential Circuits', 'easy'),
  q('circ_17', 'Which register configuration allows data to be entered bit-by-bit sequentially and read out bit-by-bit sequentially?',
    ['SISO (Serial-In Serial-Out)', 'SIPO (Serial-In Parallel-Out)', 'PISO (Parallel-In Serial-Out)', 'PIPO (Parallel-In Parallel-Out)'], 0,
    'A SISO (Serial-In Serial-Out) shift register receives data serially and shifts it out one bit per clock cycle.', 'Digital Electronics', 'Combinational & Sequential Circuits', 'easy'),
  q('circ_18', 'What is the characteristic equation of a JK flip-flop?',
    ['Q(next) = J + K’Q', 'Q(next) = JQ’ + K’Q', 'Q(next) = J’Q + KQ’', 'Q(next) = J · K'], 1,
    'The characteristic equation for a JK flip-flop is Q(next) = J · Q’ + K’ · Q.', 'Digital Electronics', 'Combinational & Sequential Circuits', 'medium'),
  q('circ_19', 'What type of hazard in combinational circuits causes a momentary unwanted glitch due to different path delays?',
    ['Static-1 Hazard', 'Dynamic Hazard', 'Both Static and Dynamic Hazards', 'Propagation Skew'], 2,
    'Static hazards (output momentarily changes when it should remain steady) and dynamic hazards (multiple transitions during one change) are caused by propagation delays.', 'Digital Electronics', 'Combinational & Sequential Circuits', 'medium'),
  q('circ_20', 'In an asynchronous (ripple) counter, how are the clock inputs of flip-flops connected?',
    ['All flip-flops receive the same master clock simultaneously', 'The output of each flip-flop serves as the clock input for the next flip-flop', 'Flip-flops are clocked randomly', 'No clock is used in ripple counters'], 1,
    'In an asynchronous/ripple counter, only the first flip-flop is clocked by the external pulse; each subsequent flip-flop is clocked by the preceding flip-flop’s output.', 'Digital Electronics', 'Combinational & Sequential Circuits', 'easy'),
];

// Topic 9: Number Systems & Computer Arithmetic
const topic9 = [
  q('num_01', 'What is the 2’s complement representation of the decimal number -13 in an 8-bit system?',
    ['11110011', '11110010', '00001101', '11110001'], 0,
    '+13 in 8-bit binary = 00001101. 1’s complement = 11110010. Add 1 = 11110011.', 'Digital Electronics', 'Number Systems & Computer Arithmetic', 'easy'),
  q('num_02', 'Convert the hexadecimal number (2F)₁₆ to its decimal equivalent:',
    ['45', '47', '52', '37'], 1,
    '(2F)₁₆ = 2 * 16¹ + 15 * 16⁰ = 32 + 15 = 47.', 'Digital Electronics', 'Number Systems & Computer Arithmetic', 'easy'),
  q('num_03', 'What is the range of signed integers that can be represented using n-bit 2’s complement notation?',
    ['-2^(n-1) to +2^(n-1)', '-2^(n-1) to +(2^(n-1) - 1)', '-(2^(n-1) - 1) to +(2^(n-1) - 1)', '0 to 2^n - 1'], 1,
    'The range of an n-bit 2’s complement number is from -2^(n-1) to +(2^(n-1) - 1). For example, with 8 bits: -128 to +127.', 'Digital Electronics', 'Number Systems & Computer Arithmetic', 'easy'),
  q('num_04', 'Why is 2’s complement widely preferred over 1’s complement in modern ALU architectures?',
    ['It is easier for humans to read', 'It eliminates the ambiguity of having two representations for zero (+0 and -0)', 'It requires fewer bits to store', 'It cannot overflow'], 1,
    '1’s complement has two representations for zero (+0 = 0000, -0 = 1111). 2’s complement has a unique zero (0000) and simpler addition hardware.', 'Digital Electronics', 'Number Systems & Computer Arithmetic', 'easy'),
  q('num_05', 'In IEEE 754 Single-Precision Floating-Point standard (32 bits), how many bits are allocated for sign, exponent, and mantissa (fraction) respectively?',
    ['1 bit sign, 8 bits exponent, 23 bits mantissa', '1 bit sign, 11 bits exponent, 20 bits mantissa', '2 bits sign, 8 bits exponent, 22 bits mantissa', '1 bit sign, 7 bits exponent, 24 bits mantissa'], 0,
    'IEEE 754 single-precision (32-bit) uses: 1 sign bit, 8 exponent bits (with bias 127), and 23 fraction/mantissa bits.', 'Digital Electronics', 'Number Systems & Computer Arithmetic', 'medium'),
  q('num_06', 'What is the excess (bias) value used in the 8-bit exponent of IEEE 754 single-precision floating-point numbers?',
    ['64', '127', '128', '255'], 1,
    'The bias for IEEE 754 single precision is 2^(8-1) - 1 = 127. Stored Exponent = Actual Exponent + 127.', 'Digital Electronics', 'Number Systems & Computer Arithmetic', 'easy'),
  q('num_07', 'Convert the binary number (110101.11)₂ to decimal:',
    ['53.75', '53.5', '51.75', '55.25'], 0,
    'Integer part: 32 + 16 + 0 + 4 + 0 + 1 = 53. Fractional part: 1 * 2⁻¹ + 1 * 2⁻² = 0.5 + 0.25 = 0.75. Result = 53.75.', 'Digital Electronics', 'Number Systems & Computer Arithmetic', 'medium'),
  q('num_08', 'What is the BCD (Binary-Coded Decimal) representation of the decimal number 89?',
    ['01011001', '10001001', '10001000', '10011000'], 1,
    'In 8421 BCD, each decimal digit is encoded as a 4-bit nibble. 8 = 1000, 9 = 1001. So 89 = 1000 1001.', 'Digital Electronics', 'Number Systems & Computer Arithmetic', 'easy'),
  q('num_09', 'When adding two BCD numbers, if the sum of a 4-bit nibble exceeds 9 or produces a carry, what correction must be added?',
    ['Add 0011 (3)', 'Add 0110 (6)', 'Add 1001 (9)', 'Subtract 0110 (6)'], 1,
    'Since 4 bits can represent 0-15 while BCD is only valid for 0-9, adding binary 6 (0110) skips the 6 invalid states.', 'Digital Electronics', 'Number Systems & Computer Arithmetic', 'medium'),
  q('num_10', 'What is the octal equivalent of the binary number (101111010)₂?',
    ['(572)₈', '(562)₈', '(574)₈', '(672)₈'], 0,
    'Group bits in threes from the right: 101 | 111 | 010 = 5 | 7 | 2 = (572)₈.', 'Digital Electronics', 'Number Systems & Computer Arithmetic', 'easy'),
  q('num_11', 'In signed arithmetic, when does an overflow condition occur when adding two signed binary numbers?',
    ['When adding two numbers of opposite signs', 'When adding two positive numbers yields a negative result, or adding two negative numbers yields a positive result', 'Whenever a carry out of the MSB occurs', 'When the result is zero'], 1,
    'Overflow in signed 2’s complement occurs if the carry into the sign bit differs from the carry out of the sign bit (C_in ⊕ C_out = 1).', 'Digital Electronics', 'Number Systems & Computer Arithmetic', 'medium'),
  q('num_12', 'What is the 1’s complement of the binary number 10101100?',
    ['01010011', '01010100', '10101101', '01010010'], 0,
    'To find the 1’s complement, invert each bit (replace 1 with 0 and 0 with 1): 10101100 becomes 01010011.', 'Digital Electronics', 'Number Systems & Computer Arithmetic', 'easy'),
  q('num_13', 'Which property makes Gray code safe for rotary shaft encoders and analog-to-digital converters?',
    ['Only a single bit changes between any two consecutive values', 'It has weighted positional values', 'It has an odd parity bit', 'It supports direct floating-point multiplication'], 0,
    'Because only one bit changes between successive positions, timing skew cannot produce erroneous intermediate values.', 'Digital Electronics', 'Number Systems & Computer Arithmetic', 'easy'),
  q('num_14', 'What is the decimal value of the Excess-3 code 1001?',
    ['9', '6', '12', '3'], 1,
    'Excess-3 code is formed by adding 3 to the decimal digit. 1001₂ = 9. Subtracting 3 gives 9 - 3 = 6.', 'Digital Electronics', 'Number Systems & Computer Arithmetic', 'easy'),
  q('num_15', 'Perform binary subtraction using 2’s complement: 7 - 4 in 4-bit representation. What is the result?',
    ['0011', '0100', '1100', '1111'], 0,
    '7 = 0111. 4 = 0100 -> -4 in 2’s complement = 1011 + 1 = 1100. 0111 + 1100 = (1)0011 (discard end-around carry) = 0011 (which is +3).', 'Digital Electronics', 'Number Systems & Computer Arithmetic', 'medium'),
  q('num_16', 'What is the base (radix) of a number system where 12 + 15 = 30?',
    ['6', '7', '8', '9'], 1,
    'In base r: (1*r + 2) + (1*r + 5) = (3*r + 0) => 2r + 7 = 3r => r = 7.', 'Digital Electronics', 'Number Systems & Computer Arithmetic', 'hard'),
  q('num_17', 'Convert the Gray code 1011 to standard binary code:',
    ['1101', '1110', '1001', '1111'], 1,
    'B3 = G3 = 1. B2 = B3 ⊕ G2 = 1 ⊕ 0 = 1. B1 = B2 ⊕ G1 = 1 ⊕ 1 = 0. B0 = B1 ⊕ G0 = 0 ⊕ 1 = 1. Wait: 1101! Let us re-verify: G=1011: B3=1, B2=1⊕0=1, B1=1⊕1=0, B0=0⊕1=1 -> 1101.', 'Digital Electronics', 'Number Systems & Computer Arithmetic', 'hard'),
  q('num_18', 'What is the maximum positive integer that can be stored in an unsigned 16-bit binary integer?',
    ['32,767', '65,535', '65,536', '131,072'], 1,
    'An n-bit unsigned integer can store values from 0 to 2^n - 1. For 16 bits: 2^16 - 1 = 65,535.', 'Digital Electronics', 'Number Systems & Computer Arithmetic', 'easy'),
  q('num_19', 'What is the ASCII value of the uppercase character "A" in decimal?',
    ['48', '65', '97', '128'], 1,
    'In ASCII encoding, "A" is 65, "B" is 66, ..., "Z" is 90. Lowercase "a" starts at 97, and "0" is 48.', 'Digital Electronics', 'Number Systems & Computer Arithmetic', 'easy'),
  q('num_20', 'In IEEE 754 standard, what do all exponent bits = 1 with a non-zero fraction represent?',
    ['Positive Infinity', 'Negative Infinity', 'NaN (Not a Number)', 'Denormalized Number'], 2,
    'When exponent is all 1s and fraction ≠ 0, it represents NaN (Not a Number), used for invalid operations like 0/0 or √(-1).', 'Digital Electronics', 'Number Systems & Computer Arithmetic', 'medium'),
];

console.log('COA & Digital topics ready: topic1:', topic1.length, 'topic7:', topic7.length, 'topic8:', topic8.length, 'topic9:', topic9.length);
module.exports = { topic1, topic7, topic8, topic9 };
