// scripts/topics_dsa.js
// Topics 10, 11, 12, 13, 14, 15, 16, 17, 18 (180 questions total - 20 per topic)

function q(id, question, options, correctAnswer, explanation, subject, topic, difficulty = 'medium') {
  return { id, question, options, correctAnswer, explanation, subject, topic, difficulty, exam: 'DSSSB TGT CS' };
}

// Topic 10: Data Structures: Arrays & Strings
const topic10 = [
  q('dsa_arr_01', 'In a 1D array A with base address B, element size S, and lower index bound L, what is the memory address formula for element A[i]?',
    ['Address = B + (i - L) * S', 'Address = B + (i + L) * S', 'Address = B + i * L * S', 'Address = B + (L - i) / S'], 0,
    'For 1D arrays: Address(A[i]) = Base + (i - LowerBound) * Size_of_element.', 'Data Structures', 'Data Structures: Arrays & Strings', 'easy'),
  q('dsa_arr_02', 'In Row-Major Order for a 2D array A[M][N] with element size c, how is the address of element A[i][j] calculated (assuming 0-based indexing)?',
    ['Base + (i * N + j) * c', 'Base + (j * M + i) * c', 'Base + (i + j) * c', 'Base + (i * M + j) * c'], 0,
    'In Row-Major Order, rows are stored consecutively: Address = Base + (i * TotalColumns + j) * c.', 'Data Structures', 'Data Structures: Arrays & Strings', 'medium'),
  q('dsa_arr_03', 'In Column-Major Order for a 2D array A[M][N] with element size c, how is the address of element A[i][j] calculated (0-based indexing)?',
    ['Base + (i * N + j) * c', 'Base + (j * M + i) * c', 'Base + (i * j) * c', 'Base + (i + j * N) * c'], 1,
    'In Column-Major Order, columns are stored consecutively: Address = Base + (j * TotalRows + i) * c.', 'Data Structures', 'Data Structures: Arrays & Strings', 'medium'),
  q('dsa_arr_04', 'What is the worst-case time complexity of inserting an element at index 0 of an unsorted dynamic array of size n?',
    ['O(1)', 'O(log n)', 'O(n)', 'O(n^2)'], 2,
    'Inserting at index 0 requires shifting all n existing elements one position to the right, taking O(n) operations.', 'Data Structures', 'Data Structures: Arrays & Strings', 'easy'),
  q('dsa_arr_05', 'What is the time complexity to access an element by its index in an array?',
    ['O(1)', 'O(n)', 'O(log n)', 'O(n log n)'], 0,
    'Arrays support direct random access via simple pointer arithmetic (Base + index * size) in O(1) constant time.', 'Data Structures', 'Data Structures: Arrays & Strings', 'easy'),
  q('dsa_arr_06', 'Which string searching algorithm preprocesses the pattern to construct a π (prefix function) table, achieving O(n + m) worst-case time complexity?',
    ['Naive string matching', 'Knuth-Morris-Pratt (KMP) Algorithm', 'Rabin-Karp Algorithm', 'Boyer-Moore Algorithm'], 1,
    'The KMP algorithm constructs a longest-proper-prefix-which-is-also-suffix (LPS) array in O(m) and matches in O(n) without backtracking the text pointer.', 'Data Structures', 'Data Structures: Arrays & Strings', 'medium'),
  q('dsa_arr_07', 'What technique does the Rabin-Karp string matching algorithm employ to achieve fast average matching?',
    ['K-d trees', 'Rolling Hash function', 'Binary Search', 'Dynamic Programming matrix'], 1,
    'Rabin-Karp uses a rolling hash to compare the hash of the pattern with sliding windows of the text in O(1) per step.', 'Data Structures', 'Data Structures: Arrays & Strings', 'medium'),
  q('dsa_arr_08', 'What is a Sparse Matrix?',
    ['A matrix containing only positive integers', 'A matrix in which the majority of elements have a value of zero', 'A matrix with equal numbers of rows and columns', 'A matrix stored in ROM'], 1,
    'A sparse matrix consists predominantly of zero elements. It is efficiently represented using coordinate lists (3-tuple: row, col, val) or Compressed Sparse Row (CSR).', 'Data Structures', 'Data Structures: Arrays & Strings', 'easy'),
  q('dsa_arr_09', 'How many elements are present in a lower triangular matrix of dimension n × n (including the main diagonal)?',
    ['n * (n - 1) / 2', 'n * (n + 1) / 2', 'n^2', '2n - 1'], 1,
    'Row 1 has 1 element, row 2 has 2, ..., row n has n. Total non-zero elements = 1 + 2 + ... + n = n(n + 1) / 2.', 'Data Structures', 'Data Structures: Arrays & Strings', 'medium'),
  q('dsa_arr_10', 'What is the length of the longest palindromic substring in the string "forgeeksskeegfor"?',
    ['8', '10', '12', '14'], 1,
    'The substring "geeksskeeg" is a symmetric palindrome of length 10.', 'Data Structures', 'Data Structures: Arrays & Strings', 'medium'),
  q('dsa_arr_11', 'In C/C++, how are string literals null-terminated in memory?',
    ['With character "0" (ASCII 48)', 'With the null byte "\\0" (ASCII 0)', 'With newline "\\n"', 'With EOF character'], 1,
    'C strings are character arrays terminated with the sentinel null character "\\0" (binary 0).', 'Data Structures', 'Data Structures: Arrays & Strings', 'easy'),
  q('dsa_arr_12', 'What is the minimum number of swaps required to reverse an array of size n in-place?',
    ['n', 'n / 2', 'n - 1', 'n * log n'], 1,
    'Reversing an array via two pointers swaps elements at i and n - 1 - i for i from 0 to floor(n/2) - 1, requiring ⌊n/2⌋ swaps.', 'Data Structures', 'Data Structures: Arrays & Strings', 'easy'),
  q('dsa_arr_13', 'Which algorithm finds the maximum subarray sum in a 1D array in O(n) linear time?',
    ['Dijkstra’s Algorithm', 'Kadane’s Algorithm', 'Kruskal’s Algorithm', 'Floyd-Warshall Algorithm'], 1,
    'Kadane’s algorithm maintains max_ending_here and max_so_far, finding the maximum contiguous subsegment sum in single linear pass O(n).', 'Data Structures', 'Data Structures: Arrays & Strings', 'easy'),
  q('dsa_arr_14', 'What is the space complexity of an in-place array rotation algorithm (e.g., reversal algorithm)?',
    ['O(1)', 'O(n)', 'O(log n)', 'O(n^2)'], 0,
    'The 3-step reversal rotation algorithm reverses subarrays in place using temporary swap variables, achieving O(1) auxiliary space.', 'Data Structures', 'Data Structures: Arrays & Strings', 'easy'),
  q('dsa_arr_15', 'What is a Tridiagonal Matrix of size n × n?',
    ['A matrix where non-zero elements appear only on the main diagonal, subdiagonal, and superdiagonal', 'A 3x3 matrix', 'A matrix with three non-zero rows', 'A matrix whose determinant is 3'], 0,
    'In a tridiagonal matrix, A[i][j] = 0 whenever |i - j| > 1, containing at most 3n - 2 non-zero elements.', 'Data Structures', 'Data Structures: Arrays & Strings', 'medium'),
  q('dsa_arr_16', 'What is the time complexity to find if two strings of length n are anagrams using a frequency counting array?',
    ['O(n^2)', 'O(n log n)', 'O(n)', 'O(1)'], 2,
    'Tallying character counts for both strings using a 26-character or 256-ASCII array takes O(n) time and O(1) auxiliary space.', 'Data Structures', 'Data Structures: Arrays & Strings', 'easy'),
  q('dsa_arr_17', 'In Dutch National Flag problem (sorting an array of 0s, 1s, and 2s), what is the optimal time and space complexity?',
    ['O(n) time and O(1) auxiliary space (single pass with 3 pointers)', 'O(n log n) time and O(n) space', 'O(n^2) time and O(1) space', 'O(n) time and O(n) space'], 0,
    'Dijkstra’s Dutch National Flag algorithm partitions 0s, 1s, and 2s in a single pass O(n) with low, mid, and high pointers and O(1) memory.', 'Data Structures', 'Data Structures: Arrays & Strings', 'medium'),
  q('dsa_arr_18', 'What is the amortized cost of inserting an element at the end of a dynamic array (like C++ std::vector or Java ArrayList) with doubling capacity?',
    ['O(n)', 'O(log n)', 'O(1)', 'O(n^2)'], 2,
    'Although occasional resizing requires copying n elements (O(n)), resizing happens exponentially infrequently, giving O(1) amortized time per append.', 'Data Structures', 'Data Structures: Arrays & Strings', 'medium'),
  q('dsa_arr_19', 'What is a jagged (ragged) array in programming?',
    ['An array whose rows can have differing lengths (an array of arrays)', 'A corrupt array in memory', 'An array containing only negative floats', 'An array sorted in descending order'], 0,
    'A jagged array is an array whose elements are themselves arrays of different dimensions and sizes.', 'Data Structures', 'Data Structures: Arrays & Strings', 'easy'),
  q('dsa_arr_20', 'Given array of size n containing integers from 1 to n with one missing number, how can the missing number be found in O(n) time and O(1) auxiliary space?',
    ['Using Expected Sum n*(n+1)/2 minus actual sum (or XOR of all elements with 1..n)', 'Sorting the array with QuickSort', 'Creating an n*n adjacency matrix', 'Using Depth First Search'], 0,
    'Sum formula (Sum = n*(n+1)/2 - sum(arr)) or XOR method computes the missing number in O(n) time and O(1) space.', 'Data Structures', 'Data Structures: Arrays & Strings', 'easy'),
];

// Topic 11: Data Structures: Stacks & Queues
const topic11 = [
  q('dsa_sq_01', 'Which data structure operates on the LIFO (Last-In, First-Out) principle?',
    ['Queue', 'Stack', 'Linked List', 'Binary Search Tree'], 1,
    'A Stack operates strictly under LIFO: the most recently inserted item (top) is the first to be removed.', 'Data Structures', 'Data Structures: Stacks & Queues', 'easy'),
  q('dsa_sq_02', 'Which data structure operates on the FIFO (First-In, First-Out) principle?',
    ['Stack', 'Queue', 'Priority Stack', 'Max Heap'], 1,
    'A Queue adheres to FIFO: items are enqueued at the rear and dequeued from the front in the order they arrived.', 'Data Structures', 'Data Structures: Stacks & Queues', 'easy'),
  q('dsa_sq_03', 'What condition occurs when attempting to POP an element from an empty stack?',
    ['Stack Overflow', 'Stack Underflow', 'Deadlock', 'Segmentation Fault'], 1,
    'Stack Underflow occurs when a POP or PEEK operation is requested on an empty stack (top == -1 or NULL).', 'Data Structures', 'Data Structures: Stacks & Queues', 'easy'),
  q('dsa_sq_04', 'What is the condition for Queue Overflow in a linear array-based queue of size MAX when rear reaches MAX - 1 even if front has advanced?',
    ['False Overflow (wasted capacity solved by Circular Queue)', 'Deadlock', 'Underflow', 'Buffer starvation'], 0,
    'In a static linear queue, when rear == MAX - 1, new items cannot be added even if front > 0, creating "false overflow".', 'Data Structures', 'Data Structures: Stacks & Queues', 'medium'),
  q('dsa_sq_05', 'In a Circular Queue implemented in an array of size N, what is the formula to advance the rear pointer during an ENQUEUE operation?',
    ['rear = rear + 1', 'rear = (rear + 1) % N', 'rear = (rear - 1) % N', 'rear = (rear + N) / 2'], 1,
    'Modulo arithmetic wraps the pointer around to index 0 when it exceeds N - 1: rear = (rear + 1) % N.', 'Data Structures', 'Data Structures: Stacks & Queues', 'easy'),
  q('dsa_sq_06', 'What is the postfix (Reverse Polish Notation) equivalent of the infix expression: A + B * C?',
    ['+ A * B C', 'A B C * +', 'A B + C *', 'A B * C +'], 1,
    'Operator precedence mandates multiplication first: (B * C) -> B C *. Then addition: A + (B C *) -> A B C * +.', 'Data Structures', 'Data Structures: Stacks & Queues', 'easy'),
  q('dsa_sq_07', 'Evaluate the following postfix expression using a stack: 6 3 2 + * 5 -',
    ['25', '30', '15', '20'], 0,
    'Push 6, 3, 2. Op "+": pop 2, 3 -> 3 + 2 = 5. Push 5. Op "*": pop 5, 6 -> 6 * 5 = 30. Push 30, 5. Op "-": pop 5, 30 -> 30 - 5 = 25.', 'Data Structures', 'Data Structures: Stacks & Queues', 'medium'),
  q('dsa_sq_08', 'Which problem is traditionally solved using a stack data structure?',
    ['Breadth-First Search (BFS)', 'Balanced Parentheses Checking (Syntax Parsing)', 'CPU Round-Robin Scheduling', 'Printer Spooling'], 1,
    'Matching delimiters (e.g., {}, [], ()) requires pushing opening brackets and popping upon encountering matching closing brackets.', 'Data Structures', 'Data Structures: Stacks & Queues', 'easy'),
  q('dsa_sq_09', 'How many stacks are minimum required to implement a FIFO Queue?',
    ['1 stack', '2 stacks', '3 stacks', '4 stacks'], 1,
    'A FIFO queue can be implemented using two stacks (inbox and outbox); items are pushed to S1, and transferred to S2 for dequeuing, reversing order to FIFO.', 'Data Structures', 'Data Structures: Stacks & Queues', 'easy'),
  q('dsa_sq_10', 'What is a Double-Ended Queue (Deque)?',
    ['A queue with two rear pointers', 'A queue where insertion and deletion can be performed at both the front and rear ends', 'A queue with two elements only', 'A priority queue'], 1,
    'A Deque (Double-Ended Queue) generalizes queues and stacks by allowing O(1) push and pop operations at both extremities.', 'Data Structures', 'Data Structures: Stacks & Queues', 'easy'),
  q('dsa_sq_11', 'In a Priority Queue, how are elements dequeued?',
    ['In the strict order they were inserted', 'The element with the highest (or lowest) priority is removed first, regardless of arrival order', 'In reverse chronological order', 'Randomly'], 1,
    'Priority queues associate a priority key with each element; items with highest priority are dequeued first (often backed by binary heaps).', 'Data Structures', 'Data Structures: Stacks & Queues', 'easy'),
  q('dsa_sq_12', 'What is the prefix notation for the infix expression: (A - B) / (C + D)?',
    ['/ - A B + C D', '- A B / + C D', '/ A B - C D +', '+ / - A B C D'], 0,
    '(A - B) -> - A B. (C + D) -> + C D. Division: / (- A B) (+ C D) -> / - A B + C D.', 'Data Structures', 'Data Structures: Stacks & Queues', 'medium'),
  q('dsa_sq_13', 'Which application relies directly on the system Call Stack?',
    ['Recursive function execution and local variable activation records', 'Disk sector defragmentation', 'Network routing packet delivery', 'Video decoding'], 0,
    'Function invocations, local variables, and return addresses are pushed onto the runtime call stack, popped when functions return.', 'Data Structures', 'Data Structures: Stacks & Queues', 'easy'),
  q('dsa_sq_14', 'What is the time complexity to find the Next Greater Element (NGE) for all elements in an array of size n using a monotonic stack?',
    ['O(n^2)', 'O(n log n)', 'O(n)', 'O(1)'], 2,
    'Each array element is pushed onto and popped from the monotonic stack at most once, yielding O(n) linear total time.', 'Data Structures', 'Data Structures: Stacks & Queues', 'medium'),
  q('dsa_sq_15', 'In an array implementation of a circular queue of size 5, if front = 2 and rear = 1, how many elements are currently in the queue?',
    ['1', '4', '3', '5'], 1,
    'Count = (rear - front + N) % N for non-empty queue: (1 - 2 + 5) % 5 = 4 elements (occupying indices 2, 3, 4, 0).', 'Data Structures', 'Data Structures: Stacks & Queues', 'hard'),
  q('dsa_sq_16', 'Which queue type is standardly used to implement Breadth-First Search (BFS) in a graph?',
    ['LIFO Stack', 'FIFO Queue', 'Priority Queue', 'Double-ended stack'], 1,
    'BFS explores vertices level-by-level using a FIFO queue to ensure vertices are visited in order of their graph distance from the root.', 'Data Structures', 'Data Structures: Stacks & Queues', 'easy'),
  q('dsa_sq_17', 'How many queues are minimum required to implement a LIFO Stack?',
    ['1 queue', '2 queues', '3 queues', 'Cannot be implemented with queues'], 1,
    'A stack can be implemented using two queues by pushing new elements to Q2, moving all elements from Q1 to Q2, and swapping names.', 'Data Structures', 'Data Structures: Stacks & Queues', 'medium'),
  q('dsa_sq_18', 'What is the time complexity of PUSH and POP operations in an optimal stack implementation?',
    ['O(1)', 'O(n)', 'O(log n)', 'O(n^2)'], 0,
    'Both PUSH and POP update only the top pointer/index, taking O(1) constant time.', 'Data Structures', 'Data Structures: Stacks & Queues', 'easy'),
  q('dsa_sq_19', 'What data structure is optimal for solving the "Stock Span Problem"?',
    ['Monotonic Decreasing Stack', 'Circular Linked List', 'Binary Search Tree', 'Hash Map'], 0,
    'A monotonic stack holding indices of elements with greater values solves the Stock Span problem in linear O(n) time.', 'Data Structures', 'Data Structures: Stacks & Queues', 'medium'),
  q('dsa_sq_20', 'What is the result of converting infix expression "A + B * C - D" to postfix?',
    ['A B C * + D -', 'A B + C * D -', 'A B C * D - +', '- + A * B C D'], 0,
    'Precedence: B * C -> B C *. Then A + (B C *) -> A B C * +. Then (A B C * +) - D -> A B C * + D -.', 'Data Structures', 'Data Structures: Stacks & Queues', 'easy'),
];

// Topic 12: Data Structures: Linked Lists
const topic12 = [
  q('dsa_ll_01', 'What is the main structural advantage of a dynamic Linked List over a fixed contiguous array?',
    ['O(1) random access to any element', 'Dynamic size allocation without requiring contiguous memory blocks', 'Less memory consumption per node', 'Better cache spatial locality'], 1,
    'Linked lists allocate nodes dynamically in heap memory anywhere available, growing or shrinking on demand without reallocation copy overhead.', 'Data Structures', 'Data Structures: Linked Lists', 'easy'),
  q('dsa_ll_02', 'In a Singly Linked List, how many pointer/reference fields does each individual node contain?',
    ['1 (next pointer)', '2 (next and prev pointers)', '3', '0'], 0,
    'A singly linked list node contains two components: data and a single "next" pointer linking to the succeeding node.', 'Data Structures', 'Data Structures: Linked Lists', 'easy'),
  q('dsa_ll_03', 'What is the time complexity to insert a new node at the head (beginning) of a singly linked list?',
    ['O(1)', 'O(n)', 'O(log n)', 'O(n^2)'], 0,
    'Inserting at head requires: new_node->next = head; head = new_node;, taking O(1) constant time.', 'Data Structures', 'Data Structures: Linked Lists', 'easy'),
  q('dsa_ll_04', 'What algorithm detects if a linked list contains a cycle (loop) using two pointers (slow and fast) in O(n) time and O(1) space?',
    ['Dijkstra’s Algorithm', 'Floyd’s Cycle-Finding Algorithm (Tortoise and Hare)', 'Prim’s Algorithm', 'Kruskal’s Algorithm'], 1,
    'Floyd’s cycle-finding algorithm moves slow by 1 step and fast by 2 steps; if a cycle exists, they will meet inside the loop.', 'Data Structures', 'Data Structures: Linked Lists', 'easy'),
  q('dsa_ll_05', 'In a Doubly Linked List, what extra pointer does each node maintain compared to a singly linked list?',
    ['Child pointer', 'Previous (prev) pointer', 'Random pointer', 'Parent pointer'], 1,
    'Doubly linked list nodes hold both "next" and "prev" pointers, allowing bidirectional traversal and O(1) deletion given a node pointer.', 'Data Structures', 'Data Structures: Linked Lists', 'easy'),
  q('dsa_ll_06', 'In a Circular Singly Linked List, where does the "next" pointer of the last node point to?',
    ['NULL', 'The Head (first) node of the list', 'The previous node', 'Itself only'], 1,
    'A circular linked list has no NULL terminator; the tail node points back to the head node, forming a continuous ring.', 'Data Structures', 'Data Structures: Linked Lists', 'easy'),
  q('dsa_ll_07', 'What is the time complexity to delete a node in a singly linked list if you are only given a pointer to that node (and not the head or previous node, assuming it is not the tail)?',
    ['O(1) by copying data from the next node and deleting the next node', 'O(n) always', 'Impossible', 'O(log n)'], 0,
    'Copying next node’s data into the current node and pointing current->next = current->next->next deletes the node in O(1) time.', 'Data Structures', 'Data Structures: Linked Lists', 'medium'),
  q('dsa_ll_08', 'How can you find the middle element of a singly linked list in a single pass?',
    ['Two pointers: slow moves 1 step while fast moves 2 steps; when fast reaches the end, slow is at the middle', 'Traversing twice: count n, then go to n/2', 'Converting to a binary tree', 'Using binary search directly on nodes'], 0,
    'The fast/slow pointer method identifies the exact middle node in a single O(n) pass using O(1) auxiliary space.', 'Data Structures', 'Data Structures: Linked Lists', 'easy'),
  q('dsa_ll_09', 'What is the time complexity to search for a specific value in an unsorted singly linked list of size n?',
    ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'], 2,
    'Because linked lists do not support indexing or pointer arithmetic, searching requires traversing nodes sequentially, taking O(n) worst-case.', 'Data Structures', 'Data Structures: Linked Lists', 'easy'),
  q('dsa_ll_10', 'How is a singly linked list reversed in-place iteratively?',
    ['Using 3 pointers: prev = NULL, curr = head, next = NULL, rewiring curr->next = prev in a loop', 'Using an external array of size n', 'By swapping data in a nested loop', 'By reversing memory addresses'], 0,
    'The standard 3-pointer iterative reversal updates pointer directions in a single O(n) pass with O(1) space.', 'Data Structures', 'Data Structures: Linked Lists', 'easy'),
  q('dsa_ll_11', 'What is the primary disadvantage of a linked list compared to an array regarding cache performance?',
    ['Linked lists are smaller', 'Non-contiguous memory allocation causes poor spatial locality, leading to frequent CPU cache misses', 'Linked lists cannot hold pointers', 'Arrays cannot hold integers'], 1,
    'Array elements reside in adjacent memory blocks preloaded into CPU cache lines. Linked list nodes are scattered across RAM, hurting cache hit ratios.', 'Data Structures', 'Data Structures: Linked Lists', 'medium'),
  q('dsa_ll_12', 'In a circular doubly linked list with a sentinel head node, what does head->prev point to?',
    ['NULL', 'The last node (tail) of the list', 'The second node', 'Itself always'], 1,
    'In a circular doubly linked list with sentinel, head->next points to the first element and head->prev points to the last element.', 'Data Structures', 'Data Structures: Linked Lists', 'easy'),
  q('dsa_ll_13', 'How can the intersection node of two singly linked lists that merge into a "Y" shape be found in O(n + m) time and O(1) space?',
    ['Calculate lengths L1 and L2, advance the longer list by |L1 - L2| steps, then advance both together until pointers match', 'Sort both linked lists', 'Hash all memory addresses using 1 GB of RAM', 'Reverse both lists'], 0,
    'Aligning the two traversal pointers by offsetting the difference in lengths allows finding the common intersection node in linear time.', 'Data Structures', 'Data Structures: Linked Lists', 'medium'),
  q('dsa_ll_14', 'What is a Skip List data structure?',
    ['A corrupted linked list', 'A probabilistic multi-level linked list that achieves O(log n) average search, insertion, and deletion times', 'A list with only even indexed nodes', 'A circular queue'], 1,
    'Skip lists maintain hierarchical forward pointer layers, skipping over nodes to emulate binary search over linked structures.', 'Data Structures', 'Data Structures: Linked Lists', 'medium'),
  q('dsa_ll_15', 'What is an XOR Linked List (Memory Efficient Doubly Linked List)?',
    ['A list where each node stores the bitwise XOR of previous and next node memory addresses in a single pointer field', 'A list where values are XORed with a secret key', 'A hardware registers array', 'A list of boolean flags'], 0,
    'An XOR linked list halves pointer overhead by storing address(prev) ⊕ address(next) in each node’s single link field.', 'Data Structures', 'Data Structures: Linked Lists', 'hard'),
  q('dsa_ll_16', 'What is the time complexity to merge two sorted singly linked lists of sizes m and n into a single sorted list?',
    ['O(m * n)', 'O(m + n)', 'O(log(m + n))', 'O((m + n) log(m + n))'], 1,
    'Merging two sorted linked lists requires comparing the current heads and splicing pointers in linear O(m + n) time.', 'Data Structures', 'Data Structures: Linked Lists', 'easy'),
  q('dsa_ll_17', 'How do you detect the start node of a cycle in a linked list using Floyd’s algorithm?',
    ['After slow and fast meet, reset slow to head; move both slow and fast 1 step at a time; their meeting point is the cycle start', 'Reverse the list and count steps', 'Delete nodes until empty', 'Run BFS from tail'], 0,
    'Mathematical proof of Floyd’s algorithm proves that the distance from head to cycle start equals the distance from the meeting point to cycle start.', 'Data Structures', 'Data Structures: Linked Lists', 'hard'),
  q('dsa_ll_18', 'What is the time complexity to insert an element at the tail of a singly linked list if maintaining a tail pointer?',
    ['O(1)', 'O(n)', 'O(log n)', 'O(n^2)'], 0,
    'With a tail pointer: tail->next = new_node; tail = new_node;, performing in O(1) constant time.', 'Data Structures', 'Data Structures: Linked Lists', 'easy'),
  q('dsa_ll_19', 'What is the time complexity to delete the tail element of a singly linked list with a tail pointer?',
    ['O(1)', 'O(n)', 'O(log n)', 'O(n^2)'], 1,
    'In a singly linked list, deleting the tail requires updating the second-to-last node’s next pointer to NULL, requiring an O(n) traversal from head.', 'Data Structures', 'Data Structures: Linked Lists', 'medium'),
  q('dsa_ll_20', 'Which sorting algorithm is most efficient and standardly preferred for sorting linked lists in-place with O(n log n) time?',
    ['Merge Sort', 'Quick Sort', 'Heap Sort', 'Radix Sort'], 0,
    'Merge Sort is ideal for linked lists because finding the middle (fast/slow pointer) and merging sublists require O(1) auxiliary pointer modifications without extra arrays.', 'Data Structures', 'Data Structures: Linked Lists', 'medium'),
];

// Topic 13: Data Structures: Trees & Binary Search Trees
const topic13 = [
  q('dsa_tree_01', 'What is the maximum number of nodes in a binary tree of height h (where a tree with a single root node has height 0)?',
    ['2^(h+1) - 1', '2^h - 1', '2^h', '2^(h-1)'], 0,
    'For height h (root at 0), level 0 has 1, level 1 has 2, ..., level h has 2^h. Sum = 2^(h+1) - 1 nodes.', 'Data Structures', 'Data Structures: Trees & Binary Search Trees', 'easy'),
  q('dsa_tree_02', 'In a Full Binary Tree (proper binary tree), what is the relationship between the number of internal nodes (I) and the number of leaf nodes (L)?',
    ['L = I + 1', 'L = I - 1', 'L = 2 * I', 'L = I'], 0,
    'In any full binary tree where every node has either 0 or 2 children, the number of leaves L is always exactly internal nodes I + 1.', 'Data Structures', 'Data Structures: Trees & Binary Search Trees', 'medium'),
  q('dsa_tree_03', 'What is the Inorder Traversal sequence for a Binary Search Tree (BST)?',
    ['Descending sorted order', 'Ascending sorted order of keys', 'Level-by-level order', 'Reverse postorder'], 1,
    'An inorder traversal (Left, Root, Right) of any valid Binary Search Tree processes keys in strictly ascending sorted order.', 'Data Structures', 'Data Structures: Trees & Binary Search Trees', 'easy'),
  q('dsa_tree_04', 'What is the order of node visits in a Preorder traversal of a binary tree?',
    ['Left, Root, Right', 'Root, Left, Right', 'Left, Right, Root', 'Root, Right, Left'], 1,
    'Preorder traversal visits the Root first, then traverses the Left subtree, and finally traverses the Right subtree.', 'Data Structures', 'Data Structures: Trees & Binary Search Trees', 'easy'),
  q('dsa_tree_05', 'What is the order of node visits in a Postorder traversal of a binary tree?',
    ['Left, Right, Root', 'Root, Left, Right', 'Left, Root, Right', 'Right, Root, Left'], 0,
    'Postorder traversal visits the Left subtree first, then the Right subtree, and finishes by processing the Root.', 'Data Structures', 'Data Structures: Trees & Binary Search Trees', 'easy'),
  q('dsa_tree_06', 'What is the worst-case time complexity of searching for a key in a skewed (unbalanced) Binary Search Tree of n nodes?',
    ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'], 2,
    'A degenerate/skewed BST behaves like a singly linked list, resulting in O(n) worst-case search complexity.', 'Data Structures', 'Data Structures: Trees & Binary Search Trees', 'easy'),
  q('dsa_tree_07', 'What is the average-case time complexity to search, insert, or delete in a balanced BST?',
    ['O(1)', 'O(log n)', 'O(n)', 'O(n^2)'], 1,
    'In balanced binary search trees, the height is bounded by O(log n), so search, insertion, and deletion all take O(log n) time.', 'Data Structures', 'Data Structures: Trees & Binary Search Trees', 'easy'),
  q('dsa_tree_08', 'When deleting a node with two children from a BST, which node can replace it to preserve the BST invariant?',
    ['Either its Inorder Predecessor (max of left subtree) or Inorder Successor (min of right subtree)', 'Any leaf node', 'The root node only', 'Its parent node'], 0,
    'Replacing the deleted node with its inorder successor or predecessor guarantees that all left keys remain smaller and right keys larger.', 'Data Structures', 'Data Structures: Trees & Binary Search Trees', 'medium'),
  q('dsa_tree_09', 'What is a Complete Binary Tree?',
    ['Every node has 2 children', 'All levels are completely filled except possibly the last, and all nodes in the last level are as far left as possible', 'A tree where all leaves are at the same level', 'A tree with height log n'], 1,
    'A complete binary tree has all levels full except possibly the last level, where leaves are populated from left to right without gaps.', 'Data Structures', 'Data Structures: Trees & Binary Search Trees', 'easy'),
  q('dsa_tree_10', 'How is a Complete Binary Tree compactly represented without pointers?',
    ['Using an array where for a node at index i: left child is at 2i+1, right child is at 2i+2, and parent is at (i-1)/2', 'Using a hash map', 'Using a stack', 'Using a circular linked list'], 0,
    'Heap structures exploit array-based complete binary tree indexing: root at 0, children of i at 2i + 1 and 2i + 2.', 'Data Structures', 'Data Structures: Trees & Binary Search Trees', 'easy'),
  q('dsa_tree_11', 'Which two traversals are sufficient to uniquely reconstruct any binary tree?',
    ['Inorder and Preorder (or Inorder and Postorder)', 'Preorder and Postorder', 'Level order only', 'Inorder only'], 0,
    'Inorder is mandatory to partition left and right subtrees; paired with either Preorder or Postorder, it uniquely determines the tree structure.', 'Data Structures', 'Data Structures: Trees & Binary Search Trees', 'medium'),
  q('dsa_tree_12', 'What is the Lowest Common Ancestor (LCA) of two nodes u and v in a Binary Search Tree?',
    ['The first node encountered during root traversal whose key value lies between u.val and v.val', 'The root node always', 'The parent of u', 'The deepest leaf'], 0,
    'In a BST, traversing from root: if both u and v are smaller, go left; if both larger, go right; the node where paths split is the LCA.', 'Data Structures', 'Data Structures: Trees & Binary Search Trees', 'medium'),
  q('dsa_tree_13', 'What is a Threaded Binary Tree?',
    ['A tree executed across multiple threads', 'A binary tree where NULL pointers are replaced by pointers (threads) to the node’s inorder predecessor or successor for traversal without recursion/stack', 'A tree with string keys', 'A tree with cycles'], 1,
    'Threaded trees make efficient use of empty leaf pointers by storing threads pointing to inorder neighbors, enabling O(1) space traversal.', 'Data Structures', 'Data Structures: Trees & Binary Search Trees', 'medium'),
  q('dsa_tree_14', 'In a binary tree, what is the diameter (or width)?',
    ['The number of nodes on the longest path between any two leaf nodes in the tree', 'The total number of levels', 'The number of leaf nodes', 'The height of the root'], 0,
    'The diameter is the length of the longest path between any two nodes in the tree, which may or may not pass through the root.', 'Data Structures', 'Data Structures: Trees & Binary Search Trees', 'medium'),
  q('dsa_tree_15', 'How can you verify if a given binary tree is a valid Binary Search Tree?',
    ['Check that left < root < right for every node within a valid [min, max] range (or verify its inorder traversal is strictly increasing)', 'Check that height is log n', 'Count leaves', 'Check that root is positive'], 0,
    'Verifying BST property requires that every node falls within an allowed (min_val, max_val) range inherited recursively from ancestors.', 'Data Structures', 'Data Structures: Trees & Binary Search Trees', 'medium'),
  q('dsa_tree_16', 'What traversal algorithm corresponds to Level-Order Traversal of a tree?',
    ['Depth-First Search (DFS)', 'Breadth-First Search (BFS) using a FIFO queue', 'Binary Search', 'Topological Sort'], 1,
    'Level-order traversal visits all nodes at depth d before proceeding to depth d + 1, implemented using a FIFO queue.', 'Data Structures', 'Data Structures: Trees & Binary Search Trees', 'easy'),
  q('dsa_tree_17', 'What is the height of a binary tree with a single node?',
    ['0 (or 1 depending on convention, typically 0 for edges, 1 for nodes)', '2', '-1', 'Infinity'], 0,
    'In standard academic convention (DSSSB / GATE), the height of a single-node tree measured by edges is 0 (or 1 measured by levels).', 'Data Structures', 'Data Structures: Trees & Binary Search Trees', 'easy'),
  q('dsa_tree_18', 'What is a Strict (or Proper) Binary Tree?',
    ['Every node has either exactly 0 or 2 children', 'All leaves are at the same depth', 'Every node has at least 1 child', 'The tree is completely balanced'], 0,
    'In a strict binary tree, no node has exactly one child; every node is either a leaf (0 children) or an internal node with 2 children.', 'Data Structures', 'Data Structures: Trees & Binary Search Trees', 'easy'),
  q('dsa_tree_19', 'If a binary tree has 15 leaf nodes, how many nodes with degree 2 does it possess?',
    ['14', '15', '16', '30'], 0,
    'In any binary tree, the number of nodes with two children n2 is related to leaf nodes n0 by: n0 = n2 + 1. Thus, n2 = n0 - 1 = 15 - 1 = 14.', 'Data Structures', 'Data Structures: Trees & Binary Search Trees', 'hard'),
  q('dsa_tree_20', 'What is the time complexity to find the maximum element in a valid Binary Search Tree of n nodes?',
    ['O(1)', 'O(h) where h is the tree height (O(log n) average, O(n) worst case)', 'O(n log n)', 'O(n^2)'], 1,
    'Finding the maximum simply follows right child pointers until right is NULL, taking time proportional to tree height O(h).', 'Data Structures', 'Data Structures: Trees & Binary Search Trees', 'easy'),
];

// Topic 14: Advanced Trees: AVL & B-Trees
const topic14 = [
  q('dsa_avl_01', 'What is an AVL Tree?',
    ['A self-balancing Binary Search Tree where the heights of the two child subtrees of any node differ by at most 1', 'A tree with 3 children per node', 'A tree stored in persistent storage', 'A complete binary heap'], 0,
    'An AVL tree (Adelson-Velsky and Landis) is a self-balancing BST with balance factor BF = Height(Left) - Height(Right) ∈ {-1, 0, +1}.', 'Data Structures', 'Advanced Trees: AVL & B-Trees', 'easy'),
  q('dsa_avl_02', 'What are the permissible Balance Factor values for any node in an AVL Tree?',
    ['-1, 0, and +1', '-2, 0, and +2', 'Any positive integer', '0 only'], 0,
    'Every node in an AVL tree must have a balance factor of -1, 0, or +1; any insertion/deletion yielding -2 or +2 triggers rebalancing rotations.', 'Data Structures', 'Advanced Trees: AVL & B-Trees', 'easy'),
  q('dsa_avl_03', 'Which single rotation is performed to restore balance when a node becomes unbalanced due to an insertion into the left subtree of the left child (LL case)?',
    ['Left Rotation', 'Right Rotation', 'Left-Right (LR) Rotation', 'Right-Left (RL) Rotation'], 1,
    'An LL imbalance is corrected by performing a single Right Rotation on the unbalanced node.', 'Data Structures', 'Advanced Trees: AVL & B-Trees', 'easy'),
  q('dsa_avl_04', 'What double rotation restores balance when an insertion occurs in the right subtree of the left child (LR case)?',
    ['Left-Right (LR) Rotation: Left rotate left child, then Right rotate node', 'Right-Left Rotation', 'Two right rotations', 'No rotation needed'], 0,
    'An LR imbalance requires a double rotation: first a Left Rotation on the left child, followed by a Right Rotation on the unbalanced root.', 'Data Structures', 'Advanced Trees: AVL & B-Trees', 'medium'),
  q('dsa_avl_05', 'What is the worst-case time complexity of search, insertion, and deletion in an AVL tree of n nodes?',
    ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'], 1,
    'Because AVL trees guarantee height h ≤ 1.44 log2(n), operations are strictly bounded by O(log n) even in the worst case.', 'Data Structures', 'Advanced Trees: AVL & B-Trees', 'easy'),
  q('dsa_avl_06', 'What is a B-Tree of order m?',
    ['A binary search tree with m levels', 'A self-balancing multi-way search tree where every internal node (except root) has between ceil(m/2) and m children', 'A tree where each node holds only 1 key', 'A binary tree stored in flash memory'], 1,
    'B-Trees are balanced multi-way trees designed for disk storage; each node contains multiple keys and references up to m children.', 'Data Structures', 'Advanced Trees: AVL & B-Trees', 'medium'),
  q('dsa_avl_07', 'Why are B-Trees and B+ Trees widely used in Database Management Systems (DBMS) and file systems rather than AVL trees?',
    ['They are easier to program in C', 'High branching factor (fan-out) minimizes disk I/O operations by keeping tree height very small', 'They use less RAM', 'They do not require keys'], 1,
    'Disk block reads are slow. A high fan-out B-tree (e.g., order 100) can store millions of records with a height of only 3 or 4, requiring minimal disk seeks.', 'Data Structures', 'Advanced Trees: AVL & B-Trees', 'medium'),
  q('dsa_avl_08', 'What is the fundamental difference between a B-Tree and a B+ Tree?',
    ['In a B-Tree, data records are stored only at leaf nodes; in a B+ Tree, data is at every node', 'In a B+ Tree, all data records are stored exclusively in leaf nodes and leaves are linked sequentially, while internal nodes store only index keys', 'B-trees cannot have more than 2 children', 'B+ trees do not support ranges'], 1,
    'B+ Trees store actual data only in leaf nodes (linked together as a doubly linked list for fast range queries), while internal nodes contain routing keys only.', 'Data Structures', 'Advanced Trees: AVL & B-Trees', 'medium'),
  q('dsa_avl_09', 'In a B-Tree of order m, what is the maximum number of keys that an internal node can hold?',
    ['m', 'm - 1', 'm / 2', '2m'], 1,
    'A node with m children can hold at most m - 1 keys.', 'Data Structures', 'Advanced Trees: AVL & B-Trees', 'easy'),
  q('dsa_avl_10', 'In a B-Tree of order m, what is the minimum number of keys in any non-root internal node?',
    ['1', 'ceil(m / 2) - 1', 'm / 2', 'm - 1'], 1,
    'Every internal node (except root) in a B-Tree of order m must have at least ⌈m/2⌉ children, hence at least ⌈m/2⌉ - 1 keys.', 'Data Structures', 'Advanced Trees: AVL & B-Trees', 'medium'),
  q('dsa_avl_11', 'What is a Red-Black Tree?',
    ['A self-balancing BST where each node is colored Red or Black and adheres to specific coloring rules ensuring no path is more than twice as long as any other', 'A tree where leaves are black and roots are white', 'A tree with 3 colors', 'A ternary tree'], 0,
    'Red-Black trees use color rules (root is black, no two consecutive reds, same black-height) to guarantee O(log n) height with faster rebalancing than AVL.', 'Data Structures', 'Advanced Trees: AVL & B-Trees', 'medium'),
  q('dsa_avl_12', 'What is the maximum number of rotations required after an insertion into an AVL tree to restore balance?',
    ['At most 2 rotations (single rotation or double rotation)', 'O(log n) rotations', 'n rotations', 'Zero rotations'], 0,
    'Inserting into an AVL tree requires at most one single or double rotation to restore balance across the entire tree.', 'Data Structures', 'Advanced Trees: AVL & B-Trees', 'medium'),
  q('dsa_avl_13', 'What is the maximum number of rotations required after a deletion from an AVL tree?',
    ['At most 1', 'At most 2', 'O(log n) rotations', 'O(n) rotations'], 2,
    'Unlike insertion, deleting from an AVL tree can cause imbalances that propagate up to the root, requiring up to O(log n) rotations.', 'Data Structures', 'Advanced Trees: AVL & B-Trees', 'hard'),
  q('dsa_avl_14', 'In a Red-Black tree, what is the color of all NULL leaf nodes (external sentinel nodes)?',
    ['Red', 'Black', 'Gray', 'Colorless'], 1,
    'By definition (Property 3 of Red-Black trees), all leaf nodes (NIL / NULL) are considered Black.', 'Data Structures', 'Advanced Trees: AVL & B-Trees', 'easy'),
  q('dsa_avl_15', 'What is the Black-Height of a node in a Red-Black tree?',
    ['The total number of nodes in its subtree', 'The number of black nodes on any simple path from that node down to a leaf node (excluding the node itself)', 'The number of red nodes', 'The height divided by 2'], 1,
    'All paths from any node to its descendant leaves must contain the exact same count of black nodes (the black-height).', 'Data Structures', 'Advanced Trees: AVL & B-Trees', 'medium'),
  q('dsa_avl_16', 'What is a Splay Tree?',
    ['A self-adjusting BST where recently accessed elements are rotated to the root using "splaying" operations (zig, zig-zig, zig-zag)', 'A static tree with read-only keys', 'A tree with ordered array leaves', 'A randomized heap'], 0,
    'Splay trees perform amortized O(log n) operations by moving recently accessed items to the root, exploiting temporal locality.', 'Data Structures', 'Advanced Trees: AVL & B-Trees', 'medium'),
  q('dsa_avl_17', 'What is a Trie (Prefix Tree) data structure primarily used for?',
    ['Numerical floating-point sorting', 'Fast prefix-based string searching, dictionary lookups, and autocomplete systems', 'Graph cycle detection', 'Matrix multiplication'], 1,
    'A Trie stores strings character by character along edges/nodes, finding a string of length L in O(L) time regardless of dictionary size.', 'Data Structures', 'Advanced Trees: AVL & B-Trees', 'easy'),
  q('dsa_avl_18', 'What is a Segment Tree?',
    ['A tree data structure for storing intervals or segments, answering range queries (range sum, range minimum) in O(log n) time', 'A tree where nodes represent memory segments', 'A tree with only 2 segments', 'A line segment graphic structure'], 0,
    'Segment trees divide intervals into halves, allowing range queries and point/range updates in O(log n) time.', 'Data Structures', 'Advanced Trees: AVL & B-Trees', 'medium'),
  q('dsa_avl_19', 'What is the minimum number of nodes in an AVL tree of height 3 (height of root = 0)?',
    ['4', '7', '8', '15'], 1,
    'Minimum nodes N(h) follows Fibonacci-like recurrence: N(0)=1, N(1)=2, N(2)=1+N(1)+N(0)=4, N(3)=1+N(2)+N(1)=1+4+2=7 nodes.', 'Data Structures', 'Advanced Trees: AVL & B-Trees', 'hard'),
  q('dsa_avl_20', 'In a B+ Tree, if a leaf node becomes overfull with m keys, how is it split?',
    ['The middle key is pushed up to the parent as a routing copy, and stays present in the leaf node', 'The middle key is deleted completely', 'The root is recreated', 'All keys are re-hashed'], 0,
    'In a B+ tree split, the middle key is copied up to the parent while remaining in the leaf to maintain data record completeness.', 'Data Structures', 'Advanced Trees: AVL & B-Trees', 'medium'),
];

// Topic 15: Data Structures: Graphs
const topic15 = [
  q('dsa_graph_01', 'What is the space complexity of storing a graph with V vertices and E edges using an Adjacency Matrix?',
    ['O(V + E)', 'O(V^2)', 'O(E^2)', 'O(V * E)'], 1,
    'An adjacency matrix allocates a V × V 2D array, consuming O(V^2) memory space regardless of the number of edges E.', 'Data Structures', 'Data Structures: Graphs', 'easy'),
  q('dsa_graph_02', 'What is the space complexity of storing a graph using an Adjacency List?',
    ['O(V^2)', 'O(V + E)', 'O(E^2)', 'O(V * E)'], 1,
    'An adjacency list stores a list of neighbors for each vertex, consuming O(V + E) space (or O(V + 2E) for undirected graphs), ideal for sparse graphs.', 'Data Structures', 'Data Structures: Graphs', 'easy'),
  q('dsa_graph_03', 'What is the time complexity of Breadth-First Search (BFS) and Depth-First Search (DFS) on a graph represented as an adjacency list?',
    ['O(V^2)', 'O(V + E)', 'O(V * E)', 'O(E log V)'], 1,
    'Both BFS and DFS visit every vertex once and examine every incident edge once, taking O(V + E) linear time with adjacency lists.', 'Data Structures', 'Data Structures: Graphs', 'easy'),
  q('dsa_graph_04', 'Which traversal algorithm uses a Stack (or recursion) to explore as deep as possible before backtracking?',
    ['Breadth-First Search (BFS)', 'Depth-First Search (DFS)', 'Dijkstra’s Algorithm', 'Kruskal’s Algorithm'], 1,
    'DFS explores paths to their maximum depth before backtracking, relying on a LIFO stack or system call recursion.', 'Data Structures', 'Data Structures: Graphs', 'easy'),
  q('dsa_graph_05', 'What is Topological Sorting of a Directed Acyclic Graph (DAG)?',
    ['Sorting vertices alphabetically', 'A linear ordering of vertices such that for every directed edge (u, v), vertex u comes before v in the ordering', 'Finding the shortest cycle', 'Sorting edges by weight'], 1,
    'Topological sorting produces a linear schedule of prerequisite tasks; it exists if and only if the graph is a Directed Acyclic Graph (DAG).', 'Data Structures', 'Data Structures: Graphs', 'medium'),
  q('dsa_graph_06', 'Which algorithm performs Topological Sorting using in-degrees of vertices and a queue?',
    ['Kahn’s Algorithm', 'Bellman-Ford Algorithm', 'Floyd-Warshall Algorithm', 'Prim’s Algorithm'], 0,
    'Kahn’s algorithm enqueues all vertices with in-degree 0, repeatedly dequeuing a vertex, reducing neighbors’ in-degrees, and enqueuing new 0 in-degree nodes.', 'Data Structures', 'Data Structures: Graphs', 'medium'),
  q('dsa_graph_07', 'How can you detect a cycle in a Directed Graph using DFS?',
    ['Checking for Cross edges', 'Checking for Back edges (an edge pointing to an ancestor currently in the active recursion stack)', 'Counting total vertices', 'Using minimum spanning tree'], 1,
    'A directed graph contains a cycle if and only if a DFS traversal discovers a Back Edge pointing to a vertex currently in the call recursion stack.', 'Data Structures', 'Data Structures: Graphs', 'medium'),
  q('dsa_graph_08', 'How can you detect a cycle in an Undirected Graph using Disjoint Set Union (DSU / Union-Find)?',
    ['For each edge (u, v), if Find(u) == Find(v), a cycle is detected; otherwise, Union(u, v)', 'By counting degree of vertices', 'By checking if edge weight is negative', 'By running binary search'], 0,
    'If both endpoints of an edge already belong to the same connected component (same root in DSU), adding that edge forms a cycle.', 'Data Structures', 'Data Structures: Graphs', 'medium'),
  q('dsa_graph_09', 'What is a Bipartite Graph?',
    ['A graph with two cycles', 'A graph whose vertices can be partitioned into two disjoint sets U and V such that every edge connects a vertex in U to one in V (2-colorable)', 'A graph with vertices having degree 2', 'A complete graph of 2 vertices'], 1,
    'A bipartite graph is 2-colorable: no edge connects two vertices of the same set. A graph is bipartite if and only if it contains no odd-length cycles.', 'Data Structures', 'Data Structures: Graphs', 'easy'),
  q('dsa_graph_10', 'A graph is Bipartite if and only if it contains NO:',
    ['Even length cycles', 'Odd length cycles', 'Self loops only', 'Directed edges'], 1,
    'Konig’s theorem proves that a graph is bipartite if and only if it contains no odd cycles (e.g., triangle of length 3 cannot be 2-colored).', 'Data Structures', 'Data Structures: Graphs', 'medium'),
  q('dsa_graph_11', 'In an undirected graph, what is the relationship between the sum of degrees of all vertices and the total number of edges E (Handshaking Lemma)?',
    ['Sum of degrees = E', 'Sum of degrees = 2 * E', 'Sum of degrees = E^2', 'Sum of degrees = E / 2'], 1,
    'The Handshaking Lemma states that each edge contributes 1 to the degree of each of its two endpoints, so Σ deg(v) = 2E.', 'Data Structures', 'Data Structures: Graphs', 'easy'),
  q('dsa_graph_12', 'According to the Handshaking Lemma, the number of vertices with odd degree in any undirected graph must always be:',
    ['Odd', 'Even', 'Zero', 'Equal to total edges'], 1,
    'Because the sum of degrees is 2E (always even), the number of odd-degree vertices must be even.', 'Data Structures', 'Data Structures: Graphs', 'medium'),
  q('dsa_graph_13', 'What is an Euler Circuit (Eulerian Tour) in an undirected connected graph?',
    ['A closed walk that visits every vertex exactly once', 'A closed walk that traverses every edge of the graph exactly once and returns to the starting vertex', 'A path between two farthest vertices', 'A tree spanning all vertices'], 1,
    'An Euler circuit traverses every edge exactly once. An undirected graph has an Euler circuit if and only if all vertices have even degree.', 'Data Structures', 'Data Structures: Graphs', 'medium'),
  q('dsa_graph_14', 'What is a Hamiltonian Cycle in a graph?',
    ['A closed loop that visits every vertex of the graph exactly once and returns to the starting vertex', 'A cycle that traverses every edge once', 'A cycle with the minimum total edge weight', 'A cycle containing only odd degree vertices'], 0,
    'A Hamiltonian cycle visits every vertex exactly once; determining if a graph has a Hamiltonian cycle is NP-Complete.', 'Data Structures', 'Data Structures: Graphs', 'easy'),
  q('dsa_graph_15', 'What is a Strongly Connected Component (SCC) in a directed graph?',
    ['A component where every vertex has an edge to every other vertex', 'A maximal subgraph in which every vertex is reachable from every other vertex within the subgraph', 'A component with no incoming edges', 'A cycle of length 3'], 1,
    'In an SCC, for any pair of vertices u and v, there exists a directed path from u to v and a directed path from v to u.', 'Data Structures', 'Data Structures: Graphs', 'medium'),
  q('dsa_graph_16', 'Which algorithm finds all Strongly Connected Components (SCCs) of a directed graph in O(V + E) time using two DFS passes and a transposed graph?',
    ['Kosaraju’s Algorithm', 'Tarjan’s Algorithm', 'Bellman-Ford Algorithm', 'Floyd-Warshall Algorithm'], 0,
    'Kosaraju’s algorithm orders vertices by finish time in pass 1, transposes edge directions, and discovers SCCs via DFS in pass 2.', 'Data Structures', 'Data Structures: Graphs', 'medium'),
  q('dsa_graph_17', 'What is an Articulation Point (Cut Vertex) in a connected graph?',
    ['A vertex with degree 1', 'A vertex whose removal increases the number of connected components (disconnects the graph)', 'The root vertex in BFS', 'A vertex with minimum edge weight'], 1,
    'Removing an articulation point splits a connected graph into two or more disconnected pieces; identified via DFS discovery times and low values.', 'Data Structures', 'Data Structures: Graphs', 'medium'),
  q('dsa_graph_18', 'What is a Bridge (Cut Edge) in a connected graph?',
    ['An edge connecting two disjoint graphs', 'An edge whose removal increases the number of connected components', 'The longest edge in a cycle', 'A self-loop'], 1,
    'A bridge is an edge whose deletion disconnects the graph, detected when low[v] > disc[u] during DFS traversal.', 'Data Structures', 'Data Structures: Graphs', 'easy'),
  q('dsa_graph_19', 'How many edges are present in a Complete Undirected Graph K_n with n vertices?',
    ['n * (n - 1) / 2', 'n * (n + 1) / 2', 'n^2', '2n - 1'], 0,
    'In K_n, each of the n vertices connects to all other n - 1 vertices: total edges = n(n - 1) / 2.', 'Data Structures', 'Data Structures: Graphs', 'easy'),
  q('dsa_graph_20', 'What is the maximum number of edges in a simple bipartite graph with n vertices?',
    ['n^2 / 4 (floor(n/2) * ceil(n/2))', 'n * (n - 1) / 2', '2n', 'n - 1'], 0,
    'Partitioning n into two equal sets of size ⌊n/2⌋ and ⌈n/2⌉ yields the complete bipartite graph K_{n/2, n/2} with at most ⌊n^2/4⌋ edges.', 'Data Structures', 'Data Structures: Graphs', 'hard'),
];

// Topic 16: Algorithms & Asymptotic Complexity
const topic16 = [
  q('dsa_asym_01', 'What does Big-O notation (O(g(n))) formally represent in algorithm analysis?',
    ['Asymptotic lower bound', 'Asymptotic upper bound (worst-case growth rate)', 'Asymptotic tight bound', 'Exact execution time in seconds'], 1,
    'f(n) = O(g(n)) means there exist positive constants c and n0 such that 0 ≤ f(n) ≤ c * g(n) for all n ≥ n0 (asymptotic upper bound).', 'Algorithms', 'Algorithms & Asymptotic Complexity', 'easy'),
  q('dsa_asym_02', 'What does Big-Omega notation (Ω(g(n))) represent?',
    ['Asymptotic upper bound', 'Asymptotic lower bound (best-case growth rate)', 'Asymptotic tight bound', 'Average-case execution time'], 1,
    'f(n) = Ω(g(n)) means there exist c > 0 and n0 such that f(n) ≥ c * g(n) for all n ≥ n0 (asymptotic lower bound).', 'Algorithms', 'Algorithms & Asymptotic Complexity', 'easy'),
  q('dsa_asym_03', 'What does Big-Theta notation (Θ(g(n))) represent?',
    ['Asymptotic tight bound (f(n) is bounded both above and below by g(n))', 'Worst-case bound only', 'Best-case bound only', 'Exponential growth'], 0,
    'f(n) = Θ(g(n)) if and only if f(n) = O(g(n)) and f(n) = Ω(g(n)) simultaneously.', 'Algorithms', 'Algorithms & Asymptotic Complexity', 'easy'),
  q('dsa_asym_04', 'Arrange the following functions in increasing order of asymptotic growth rate: O(n!), O(n log n), O(1), O(n^2), O(2^n).',
    ['O(1) < O(n log n) < O(n^2) < O(2^n) < O(n!)', 'O(1) < O(n^2) < O(n log n) < O(2^n) < O(n!)', 'O(n!) < O(2^n) < O(n^2) < O(n log n) < O(1)', 'O(1) < O(n log n) < O(2^n) < O(n^2) < O(n!)'], 0,
    'Constant O(1) < Log-linear O(n log n) < Quadratic O(n^2) < Exponential O(2^n) < Factorial O(n!).', 'Algorithms', 'Algorithms & Asymptotic Complexity', 'easy'),
  q('dsa_asym_05', 'According to the Master Theorem for recurrences of the form T(n) = a*T(n/b) + f(n), if f(n) = Θ(n^(log_b(a))), what is the solution?',
    ['T(n) = Θ(n^(log_b(a)))', 'T(n) = Θ(n^(log_b(a)) * log n)', 'T(n) = Θ(f(n))', 'T(n) = Θ(n^2)'], 1,
    'Case 2 of Master Theorem: when f(n) = Θ(n^(log_b(a))), the solution is T(n) = Θ(n^(log_b(a)) * log n).', 'Algorithms', 'Algorithms & Asymptotic Complexity', 'medium'),
  q('dsa_asym_06', 'Solve the recurrence relation for Merge Sort: T(n) = 2*T(n/2) + Θ(n). What is T(n)?',
    ['Θ(n)', 'Θ(n log n)', 'Θ(n^2)', 'Θ(log n)'], 1,
    'Here a = 2, b = 2, log_b(a) = log2(2) = 1. Since f(n) = Θ(n^1), Master Theorem Case 2 gives T(n) = Θ(n log n).', 'Algorithms', 'Algorithms & Asymptotic Complexity', 'easy'),
  q('dsa_asym_07', 'Solve the recurrence relation: T(n) = T(n - 1) + 1 with base case T(1) = 1.',
    ['O(log n)', 'O(n)', 'O(n^2)', 'O(2^n)'], 1,
    'T(n) = T(n-1) + 1 = T(n-2) + 2 = ... = T(1) + (n - 1) = 1 + n - 1 = n -> O(n).', 'Algorithms', 'Algorithms & Asymptotic Complexity', 'easy'),
  q('dsa_asym_08', 'What is the solution to the recurrence relation: T(n) = 2*T(n - 1) + 1 with T(1) = 1 (Towers of Hanoi)?',
    ['O(n)', 'O(n^2)', 'O(2^n)', 'O(n log n)'], 2,
    'T(n) = 2^n - 1 -> O(2^n) exponential time complexity.', 'Algorithms', 'Algorithms & Asymptotic Complexity', 'easy'),
  q('dsa_asym_09', 'What is Little-o notation (o(g(n)))?',
    ['Upper bound that is asymptotically tight', 'Strict upper bound that is not asymptotically tight (lim_{n->inf} f(n)/g(n) = 0)', 'Lower bound', 'Average case bound'], 1,
    'Little-o represents a strict upper bound: f(n) grows strictly slower than g(n), meaning f(n)/g(n) approaches 0 as n approaches infinity.', 'Algorithms', 'Algorithms & Asymptotic Complexity', 'medium'),
  q('dsa_asym_10', 'Solve the recurrence relation: T(n) = 4*T(n/2) + n.',
    ['Θ(n)', 'Θ(n log n)', 'Θ(n^2)', 'Θ(n^3)'], 2,
    'a = 4, b = 2 -> n^(log_b a) = n^(log2 4) = n^2. Since f(n) = n is polynomially smaller than n^2 (Case 1), T(n) = Θ(n^2).', 'Algorithms', 'Algorithms & Asymptotic Complexity', 'medium'),
  q('dsa_asym_11', 'Solve the recurrence relation for Binary Search: T(n) = T(n/2) + O(1).',
    ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'], 1,
    'a = 1, b = 2 -> n^(log2 1) = n^0 = 1. By Master Theorem Case 2, T(n) = Θ(log n).', 'Algorithms', 'Algorithms & Asymptotic Complexity', 'easy'),
  q('dsa_asym_12', 'What is the time complexity of the following code snippet?\nfor (int i = 1; i <= n; i *= 2) { /* O(1) ops */ }',
    ['O(n)', 'O(log n)', 'O(n log n)', 'O(1)'], 1,
    'The loop variable i doubles in each iteration: 1, 2, 4, 8, ..., 2^k. Terminating when 2^k ≥ n gives k = ⌈log2(n)⌉ iterations.', 'Algorithms', 'Algorithms & Asymptotic Complexity', 'easy'),
  q('dsa_asym_13', 'What is the time complexity of the following nested loop?\nfor (int i = 0; i < n; i++) for (int j = 0; j < i; j++) { /* O(1) ops */ }',
    ['O(n)', 'O(n log n)', 'O(n^2)', 'O(n^3)'], 2,
    'Total inner loop executions = 0 + 1 + 2 + ... + (n - 1) = n(n - 1)/2 = O(n^2).', 'Algorithms', 'Algorithms & Asymptotic Complexity', 'easy'),
  q('dsa_asym_14', 'What is "Amortized Analysis" in algorithm design?',
    ['Analyzing worst-case time of a single operation in isolation', 'Averaging the running time per operation over a sequence of operations to guarantee average performance bound', 'Measuring CPU temperature during sorting', 'Estimating memory usage in cache'], 1,
    'Amortized analysis guarantees the average performance of each operation in the worst-case sequence (e.g., dynamic array resizing, disjoint set union).', 'Algorithms', 'Algorithms & Asymptotic Complexity', 'medium'),
  q('dsa_asym_15', 'What are the three common techniques used to perform Amortized Analysis?',
    ['Aggregate method, Accounting (Banker’s) method, Potential method', 'Top-down, Bottom-up, Divide-and-conquer', 'Greedy, DP, Backtracking', 'Master Theorem, Substitution, Recursion tree'], 0,
    'The standard methods for amortized analysis are the Aggregate analysis, Accounting method, and Potential (physicist’s) method.', 'Algorithms', 'Algorithms & Asymptotic Complexity', 'medium'),
  q('dsa_asym_16', 'What is the complexity class P in computational complexity theory?',
    ['Problems solvable by a deterministic Turing machine in polynomial time O(n^k)', 'Problems verified in polynomial time', 'Problems requiring exponential time', 'Problems that cannot be solved by any algorithm'], 0,
    'Class P consists of decision problems that can be solved by a deterministic algorithm in polynomial time.', 'Algorithms', 'Algorithms & Asymptotic Complexity', 'easy'),
  q('dsa_asym_17', 'What is the complexity class NP?',
    ['Non-Polynomial problems', 'Decision problems for which a given solution certificate can be verified in polynomial time by a deterministic Turing machine', 'Problems that can never be solved', 'Problems with negative weights'], 1,
    'NP (Nondeterministic Polynomial time) contains decision problems verifiable in polynomial time given a certificate.', 'Algorithms', 'Algorithms & Asymptotic Complexity', 'easy'),
  q('dsa_asym_18', 'What defines an NP-Complete problem?',
    ['It is in NP, and every problem in NP can be polynomial-time reduced to it (NP-Hard)', 'It can be solved in O(n) time', 'It is unsolvable', 'It has no verification algorithm'], 0,
    'A problem X is NP-Complete if X ∈ NP and for all Y ∈ NP, Y ≤_p X. They are the hardest problems in NP.', 'Algorithms', 'Algorithms & Asymptotic Complexity', 'medium'),
  q('dsa_asym_19', 'Which of the following problems is known to be NP-Complete?',
    ['Shortest Path (Dijkstra)', 'Minimum Spanning Tree (Kruskal)', '0/1 Knapsack Problem (and Traveling Salesperson Problem decision version)', 'Sorting an array (Merge Sort)'], 2,
    'The 0/1 Knapsack problem, Boolean Satisfiability (SAT), and Traveling Salesperson decision problem are NP-Complete.', 'Algorithms', 'Algorithms & Asymptotic Complexity', 'medium'),
  q('dsa_asym_20', 'What is Cook’s Theorem (Cook-Levin Theorem)?',
    ['Proves that Merge Sort is optimal', 'Proves that the Boolean Satisfiability problem (SAT) is NP-Complete', 'Proves that P = NP', 'Proves that QuickSort is O(n log n)'], 1,
    'The Cook-Levin theorem established the existence of NP-complete problems by proving that SAT is NP-Complete.', 'Algorithms', 'Algorithms & Asymptotic Complexity', 'hard'),
];

// Topic 17: Searching & Sorting Algorithms
const topic17 = [
  q('dsa_sort_01', 'What is the worst-case and best-case time complexity of Linear Search in an array of size n?',
    ['Worst: O(n), Best: O(1)', 'Worst: O(log n), Best: O(1)', 'Worst: O(n log n), Best: O(n)', 'Worst: O(n^2), Best: O(n)'], 0,
    'Linear search checks elements one by one: best case is finding target at index 0 (O(1)), worst case is not present or at last index (O(n)).', 'Algorithms', 'Searching & Sorting Algorithms', 'easy'),
  q('dsa_sort_02', 'What prerequisite MUST be satisfied by an array before Binary Search can be applied?',
    ['The array must have an even number of elements', 'The elements in the array must be sorted in ascending or descending order', 'The array must contain no duplicate values', 'The array must be stored in a linked list'], 1,
    'Binary search repeatedly divides the search space in half, which relies fundamentally on elements being sorted.', 'Algorithms', 'Searching & Sorting Algorithms', 'easy'),
  q('dsa_sort_03', 'What is the worst-case and average-case time complexity of Binary Search on a sorted array of n elements?',
    ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'], 1,
    'With each comparison, binary search cuts the search space in half (n, n/2, n/4, ..., 1), taking O(log2 n) time.', 'Algorithms', 'Searching & Sorting Algorithms', 'easy'),
  q('dsa_sort_04', 'What is the worst-case and average-case time complexity of Bubble Sort?',
    ['O(n log n)', 'O(n^2)', 'O(n)', 'O(log n)'], 1,
    'Standard Bubble Sort makes (n-1) passes with adjacent comparisons, taking O(n^2) comparisons and swaps in worst and average cases.', 'Algorithms', 'Searching & Sorting Algorithms', 'easy'),
  q('dsa_sort_05', 'How can Bubble Sort be optimized to achieve O(n) best-case time complexity on an already sorted array?',
    ['Using recursion', 'Using a boolean swapped flag that terminates the algorithm early if no swaps occurred during a pass', 'Sorting in reverse', 'Using binary search'], 1,
    'If a pass completes with 0 swaps, the array is already sorted and the algorithm terminates immediately after O(n) comparisons.', 'Algorithms', 'Searching & Sorting Algorithms', 'easy'),
  q('dsa_sort_06', 'Which sorting algorithm repeatedly finds the minimum element from the unsorted sublist and swaps it with the first unsorted element?',
    ['Insertion Sort', 'Selection Sort', 'Bubble Sort', 'Merge Sort'], 1,
    'Selection Sort divides the array into sorted and unsorted regions, finding the minimum in the unsorted section in each iteration.', 'Algorithms', 'Searching & Sorting Algorithms', 'easy'),
  q('dsa_sort_07', 'What is the best, average, and worst-case time complexity of Selection Sort?',
    ['Best: O(n), Average: O(n log n), Worst: O(n^2)', 'O(n^2) in all cases (best, average, and worst)', 'Best: O(1), Worst: O(n log n)', 'O(n log n) in all cases'], 1,
    'Selection Sort always executes n(n - 1)/2 comparisons regardless of initial array ordering, so it is strictly Θ(n^2) in all cases.', 'Algorithms', 'Searching & Sorting Algorithms', 'easy'),
  q('dsa_sort_08', 'Which sorting algorithm is most efficient and takes O(n) time when the input array is already sorted or nearly sorted?',
    ['Insertion Sort', 'Selection Sort', 'Heap Sort', 'Merge Sort'], 0,
    'Insertion sort performs only 1 comparison per element on an already sorted array, achieving O(n) best-case linear time.', 'Algorithms', 'Searching & Sorting Algorithms', 'easy'),
  q('dsa_sort_09', 'What algorithmic design paradigm does Merge Sort follow?',
    ['Greedy method', 'Dynamic Programming', 'Divide and Conquer', 'Backtracking'], 2,
    'Merge Sort divides the array into two halves, recursively sorts each half, and merges the sorted halves back together.', 'Algorithms', 'Searching & Sorting Algorithms', 'easy'),
  q('dsa_sort_10', 'What is the time complexity of Merge Sort in the best, average, and worst cases?',
    ['O(n^2)', 'O(n log n) in all cases', 'Best: O(n), Worst: O(n^2)', 'O(log n)'], 1,
    'Merge Sort consistently divides the problem in half and does O(n) work per level: T(n) = 2T(n/2) + O(n) = Θ(n log n) across all cases.', 'Algorithms', 'Searching & Sorting Algorithms', 'easy'),
  q('dsa_sort_11', 'What is the auxiliary space complexity of standard Merge Sort on an array of size n?',
    ['O(1)', 'O(n)', 'O(log n)', 'O(n^2)'], 1,
    'Merging two array segments requires an auxiliary buffer array of size n, giving O(n) auxiliary memory overhead.', 'Algorithms', 'Searching & Sorting Algorithms', 'easy'),
  q('dsa_sort_12', 'What is the worst-case time complexity of QuickSort, and when does it typically occur with naive first-element pivot selection?',
    ['O(n^2), when the array is already sorted in ascending or descending order', 'O(n log n), always', 'O(n), on random data', 'O(log n), on reverse sorted data'], 0,
    'If the chosen pivot is always the smallest or largest element, the partition is unbalanced (size 0 and n - 1), yielding O(n^2) worst-case time.', 'Algorithms', 'Searching & Sorting Algorithms', 'medium'),
  q('dsa_sort_13', 'What is the average-case time complexity of QuickSort?',
    ['O(n^2)', 'O(n log n)', 'O(n)', 'O(log n)'], 1,
    'On average, random pivots create balanced partitions, giving the recurrence T(n) = 2T(n/2) + O(n), which solves to Θ(n log n).', 'Algorithms', 'Searching & Sorting Algorithms', 'easy'),
  q('dsa_sort_14', 'What technique avoids the O(n^2) worst case in QuickSort in practice?',
    ['Randomized pivot selection or Median-of-Three pivot strategy', 'Choosing index 0 always', 'Using 2 pivots always', 'Replacing partition with linear search'], 0,
    'Randomized QuickSort picks a random pivot or median-of-three (first, middle, last), making the worst-case input vanishingly improbable.', 'Algorithms', 'Searching & Sorting Algorithms', 'easy'),
  q('dsa_sort_15', 'What does it mean for a sorting algorithm to be "Stable"?',
    ['It does not crash', 'It preserves the relative order of equal keys (records with identical keys appear in the same order in the output as in the input)', 'It uses O(1) memory', 'It runs in O(n log n) time'], 1,
    'A sorting algorithm is stable if two objects with equal keys appear in the same relative order in the sorted output as in the original input.', 'Algorithms', 'Searching & Sorting Algorithms', 'easy'),
  q('dsa_sort_16', 'Which of the following sorting algorithms is inherently UNSTABLE?',
    ['Merge Sort', 'Insertion Sort', 'Heap Sort (and QuickSort)', 'Bubble Sort'], 2,
    'Heap Sort, QuickSort, and Selection Sort are inherently unstable because long-distance swaps can alter the relative order of identical keys.', 'Algorithms', 'Searching & Sorting Algorithms', 'medium'),
  q('dsa_sort_17', 'What is the worst-case time complexity of Heap Sort on an array of size n?',
    ['O(n^2)', 'O(n log n)', 'O(n)', 'O(log n)'], 1,
    'Building the heap takes O(n), and extracting n elements takes n * O(log n) = O(n log n) time in all cases.', 'Algorithms', 'Searching & Sorting Algorithms', 'easy'),
  q('dsa_sort_18', 'What is the theoretical lower bound on time complexity for any Comparison-based sorting algorithm in the worst case?',
    ['Ω(n)', 'Ω(n log n)', 'Ω(n^2)', 'Ω(log n)'], 1,
    'Any comparison sort can be modeled as a decision tree with n! leaves; minimum tree depth is log2(n!) = Ω(n log n).', 'Algorithms', 'Searching & Sorting Algorithms', 'medium'),
  q('dsa_sort_19', 'Which non-comparison sorting algorithm sorts n integers within a range of 0 to k in O(n + k) time and O(k) space?',
    ['Counting Sort', 'QuickSort', 'Heap Sort', 'Merge Sort'], 0,
    'Counting Sort counts occurrences of each key into an array of size k, running in O(n + k) time without element-to-element comparisons.', 'Algorithms', 'Searching & Sorting Algorithms', 'easy'),
  q('dsa_sort_20', 'What is Radix Sort and what is its time complexity for n d-digit numbers with base b?',
    ['O(d * (n + b))', 'O(n^2)', 'O(n log n)', 'O(2^n)'], 0,
    'Radix Sort processes numbers digit-by-digit (LSD or MSD) using a stable subroutine like counting sort, taking O(d * (n + b)) linear time.', 'Algorithms', 'Searching & Sorting Algorithms', 'medium'),
];

// Topic 18: Graph Algorithms & Dynamic Programming
const topic18 = [
  q('dsa_gadp_01', 'What algorithm finds the Single-Source Shortest Path in a weighted graph with NON-NEGATIVE edge weights?',
    ['Dijkstra’s Algorithm', 'Bellman-Ford Algorithm', 'Floyd-Warshall Algorithm', 'Kruskal’s Algorithm'], 0,
    'Dijkstra’s algorithm uses a greedy approach with a priority queue to compute shortest paths in O((V + E) log V) time for non-negative edges.', 'Algorithms', 'Graph Algorithms & Dynamic Programming', 'easy'),
  q('dsa_gadp_02', 'Why does Dijkstra’s Algorithm fail on graphs with negative edge weights?',
    ['It causes an infinite loop', 'The greedy choice assumption (that visited nodes have finalized minimal distances) fails when negative weights can reduce path lengths later', 'It cannot use adjacency lists', 'Priority queues cannot store negative numbers'], 1,
    'Dijkstra permanently marks vertices as visited; a negative edge discovered later could yield a shorter path to an already finalized vertex.', 'Algorithms', 'Graph Algorithms & Dynamic Programming', 'medium'),
  q('dsa_gadp_03', 'Which algorithm solves Single-Source Shortest Path on graphs that may contain NEGATIVE edge weights, and can detect negative weight cycles?',
    ['Bellman-Ford Algorithm', 'Dijkstra’s Algorithm', 'Prim’s Algorithm', 'Boruvka’s Algorithm'], 0,
    'Bellman-Ford relaxes all E edges V - 1 times, running in O(V * E) time; an extra relaxation pass that decreases distances indicates a negative cycle.', 'Algorithms', 'Graph Algorithms & Dynamic Programming', 'easy'),
  q('dsa_gadp_04', 'What is the time complexity of the Floyd-Warshall All-Pairs Shortest Path algorithm for a graph with V vertices?',
    ['O(V + E)', 'O(V * E)', 'O(V^3)', 'O(E log V)'], 2,
    'Floyd-Warshall uses 3 nested loops from 1 to V to update dist[i][j] = min(dist[i][j], dist[i][k] + dist[k][j]), taking Θ(V^3) time.', 'Algorithms', 'Graph Algorithms & Dynamic Programming', 'easy'),
  q('dsa_gadp_05', 'What is a Minimum Spanning Tree (MST) of a connected weighted undirected graph?',
    ['A cycle with maximum weight', 'A subgraph that connects all V vertices with exactly V - 1 edges while minimizing total edge weight, without forming any cycles', 'A path connecting the two farthest nodes', 'A tree of height 1'], 1,
    'An MST is a tree spanning all V vertices with V - 1 edges and minimum possible total weight sum.', 'Algorithms', 'Graph Algorithms & Dynamic Programming', 'easy'),
  q('dsa_gadp_06', 'How does Kruskal’s Algorithm construct a Minimum Spanning Tree?',
    ['Sorts all edges in ascending order of weight and greedily adds the smallest edge that does not create a cycle using Disjoint Set Union (DSU)', 'Grows a tree from a single start vertex', 'Relaxes edges V - 1 times', 'Uses a matrix multiplication loop'], 0,
    'Kruskal’s algorithm sorts edges in O(E log E) time and uses Union-Find to add edges that connect different components.', 'Algorithms', 'Graph Algorithms & Dynamic Programming', 'easy'),
  q('dsa_gadp_07', 'How does Prim’s Algorithm construct a Minimum Spanning Tree?',
    ['Sorts all edges globally', 'Starts from an arbitrary root vertex and grows a single tree by greedily adding the cheapest edge connecting the tree to a non-tree vertex', 'Removes maximum weight edges in cycles', 'Uses dynamic programming matrix'], 1,
    'Prim’s algorithm maintains a growing tree cut, picking the minimum weight cross-boundary edge at each step via a priority queue.', 'Algorithms', 'Graph Algorithms & Dynamic Programming', 'easy'),
  q('dsa_gadp_08', 'What is the time complexity of Prim’s and Kruskal’s algorithms using modern binary heaps and Disjoint Set Union?',
    ['O(V^3)', 'O(E log V)', 'O(V * E)', 'O(V^2)'], 1,
    'Both Kruskal’s (sorting edges) and Prim’s (min-heap for cut edges) run in O(E log V) time.', 'Algorithms', 'Graph Algorithms & Dynamic Programming', 'medium'),
  q('dsa_gadp_09', 'What are the two core properties that a problem MUST possess for Dynamic Programming to be applicable?',
    ['Optimal Substructure and Overlapping Subproblems', 'Greedy Choice Property and Divide and Conquer', 'NP-Completeness and Polynomial Verification', 'Associativity and Commutativity'], 0,
    'Dynamic Programming applies when a problem exhibits Optimal Substructure (optimal solution built from sub-solutions) and Overlapping Subproblems (subproblems recur repeatedly).', 'Algorithms', 'Graph Algorithms & Dynamic Programming', 'easy'),
  q('dsa_gadp_10', 'What is the difference between Memoization (Top-Down) and Tabulation (Bottom-Up) in Dynamic Programming?',
    ['Memoization uses recursion with a lookup cache; Tabulation iteratively fills an array starting from base cases', 'Memoization is greedy; Tabulation is divide-and-conquer', 'Tabulation uses recursion; Memoization does not', 'There is no difference'], 0,
    'Top-down Memoization caches results of recursive calls on-demand; bottom-up Tabulation constructs solutions systematically starting from base cases in loops.', 'Algorithms', 'Graph Algorithms & Dynamic Programming', 'easy'),
  q('dsa_gadp_11', 'What is the time and space complexity of solving the 0/1 Knapsack problem with n items and capacity W using Dynamic Programming?',
    ['O(n * W) time and O(n * W) or O(W) space', 'O(2^n) time and O(1) space', 'O(n log n) time and O(n) space', 'O(W^2) time and O(n) space'], 0,
    'The 2D table DP[i][w] computes solutions in O(n * W) pseudo-polynomial time, optimizable to O(W) space with a 1D array.', 'Algorithms', 'Graph Algorithms & Dynamic Programming', 'medium'),
  q('dsa_gadp_12', 'Why is the Dynamic Programming solution to the 0/1 Knapsack problem described as "Pseudo-Polynomial"?',
    ['Because it is a polynomial time algorithm for all inputs', 'Because its runtime depends on the numeric value of W, which is exponential in the number of bits required to represent W', 'Because it uses fake polynomials', 'Because it runs in O(n log n)'], 1,
    'Since W requires log2(W) bits to represent, O(n * W) is exponential in the input length of W, making it pseudo-polynomial.', 'Algorithms', 'Graph Algorithms & Dynamic Programming', 'hard'),
  q('dsa_gadp_13', 'How can the Fractional Knapsack problem be solved optimally in O(n log n) time?',
    ['Using 0/1 Dynamic Programming', 'Using a Greedy algorithm: sort items by value-to-weight ratio (v_i / w_i) in descending order and take items greedily', 'Using Bellman-Ford algorithm', 'Using Floyd-Warshall algorithm'], 1,
    'Because items can be divided into fractions, picking the highest density (value/weight) first is provably optimal (Greedy approach).', 'Algorithms', 'Graph Algorithms & Dynamic Programming', 'easy'),
  q('dsa_gadp_14', 'What is the recurrence relation for the Longest Common Subsequence (LCS) of strings X[1..m] and Y[1..n] when X[i] == Y[j]?',
    ['LCS[i][j] = LCS[i - 1][j - 1] + 1', 'LCS[i][j] = max(LCS[i - 1][j], LCS[i][j - 1])', 'LCS[i][j] = LCS[i - 1][j - 1]', 'LCS[i][j] = 0'], 0,
    'When the characters match, the LCS length increments by 1: LCS(i, j) = 1 + LCS(i - 1, j - 1).', 'Algorithms', 'Graph Algorithms & Dynamic Programming', 'easy'),
  q('dsa_gadp_15', 'What is the time complexity to find the Longest Common Subsequence of two strings of lengths m and n using Dynamic Programming?',
    ['O(m * n)', 'O(m + n)', 'O(2^(m+n))', 'O(m log n)'], 0,
    'Filling the m × n table takes O(m * n) time and O(m * n) (or O(min(m, n))) space.', 'Algorithms', 'Graph Algorithms & Dynamic Programming', 'easy'),
  q('dsa_gadp_16', 'What is Matrix Chain Multiplication problem primarily trying to minimize?',
    ['The size of the output matrix', 'The total number of scalar multiplications required to multiply a chain of matrices A1 * A2 * ... * An', 'The number of matrices', 'The time to read matrices from disk'], 1,
    'Because matrix multiplication is associative ((AB)C = A(BC)), parenthesization drastically affects the number of scalar multiplications needed.', 'Algorithms', 'Graph Algorithms & Dynamic Programming', 'medium'),
  q('dsa_gadp_17', 'What is the time complexity of solving the Matrix Chain Multiplication problem for n matrices using Dynamic Programming?',
    ['O(n^2)', 'O(n^3)', 'O(2^n)', 'O(n log n)'], 1,
    'Computing cost for subchains of length 2 to n requires trying all split points k, yielding O(n^3) total time.', 'Algorithms', 'Graph Algorithms & Dynamic Programming', 'medium'),
  q('dsa_gadp_18', 'What is the Edit Distance (Levenshtein Distance) between two strings?',
    ['The length of their longest common prefix', 'The minimum number of single-character operations (insertions, deletions, substitutions) required to transform one string into the other', 'The difference in their ASCII sums', 'The Hamming distance between them'], 1,
    'Levenshtein distance computes minimal edits (insert, delete, replace) via an O(m * n) DP table.', 'Algorithms', 'Graph Algorithms & Dynamic Programming', 'easy'),
  q('dsa_gadp_19', 'What is the time complexity to find the Longest Increasing Subsequence (LIS) of an array of size n using Patience Sorting and Binary Search?',
    ['O(n^2)', 'O(n log n)', 'O(n)', 'O(2^n)'], 1,
    'While standard DP takes O(n^2), maintaining the tails of active candidate lists with binary search solves LIS in O(n log n) time.', 'Algorithms', 'Graph Algorithms & Dynamic Programming', 'medium'),
  q('dsa_gadp_20', 'Which problem asks to find a maximum flow through a flow network from source s to sink t?',
    ['Shortest Path', 'Ford-Fulkerson Method (Edmonds-Karp Algorithm)', 'Minimum Spanning Tree', 'Traveling Salesperson'], 1,
    'The Ford-Fulkerson method (implemented via BFS in Edmonds-Karp O(V * E^2)) computes the maximum flow in a directed capacity network.', 'Algorithms', 'Graph Algorithms & Dynamic Programming', 'medium'),
];

console.log('DSA topics ready: topic10:', topic10.length, 'topic11:', topic11.length, 'topic12:', topic12.length, 'topic13:', topic13.length, 'topic14:', topic14.length, 'topic15:', topic15.length, 'topic16:', topic16.length, 'topic17:', topic17.length, 'topic18:', topic18.length);
module.exports = { topic10, topic11, topic12, topic13, topic14, topic15, topic16, topic17, topic18 };
