import React, { useState, useEffect } from 'react';
import { GeneratedContentPack, PlatformTarget } from '../../types';
import { IndexedDbService } from '../../services/indexedDbService';
import { BrandKitService } from '../../services/brandKitService';
import {
  ConversionTrackingService,
  UtmParams,
} from '../../services/conversionTrackingService';
import {
  TrendingUp,
  Link,
  Eye,
  Heart,
  MessageSquare,
  Share2,
  Bookmark,
  UserPlus,
  MousePointer,
  Download,
  Copy,
  Check,
  ArrowLeft,
  Filter,
  Layers,
  Sparkles,
} from 'lucide-react';

interface ConversionTrackingViewProps {
  onBack?: () => void;
}

export const ConversionTrackingView: React.FC<ConversionTrackingViewProps> = ({ onBack }) => {
  const [packs, setPacks] = useState<GeneratedContentPack[]>([]);
  const [copiedUtm, setCopiedUtm] = useState<boolean>(false);
  const [selectedPackForEdit, setSelectedPackForEdit] = useState<GeneratedContentPack | null>(null);

  // UTM Builder Form
  const brandKit = BrandKitService.getBrandKit();
  const [utmSource, setUtmSource] = useState<string>('instagram');
  const [utmMedium, setUtmMedium] = useState<string>('reel');
  const [utmCampaign, setUtmCampaign] = useState<string>('dsssb_cs_marathon');
  const [utmContent, setUtmContent] = useState<string>('BP-DSSSB-DBMS-2026-001');

  // Manual Log Metric State
  const [logViews, setLogViews] = useState<number>(0);
  const [logLikes, setLogLikes] = useState<number>(0);
  const [logComments, setLogComments] = useState<number>(0);
  const [logShares, setLogShares] = useState<number>(0);
  const [logSaves, setLogSaves] = useState<number>(0);
  const [logFollowers, setLogFollowers] = useState<number>(0);
  const [logClicks, setLogClicks] = useState<number>(0);
  const [logInstalls, setLogInstalls] = useState<number>(0);
  const [logPostUrl, setLogPostUrl] = useState<string>('');

  useEffect(() => {
    IndexedDbService.getAllContentPacks().then(loaded => {
      setPacks(loaded);
      if (loaded.length > 0) {
        setUtmContent(loaded[0].contentId || loaded[0].id);
      }
    });
  }, []);

  const metrics = ConversionTrackingService.aggregateMetrics(packs);
  const generatedUtmUrl = ConversionTrackingService.buildUtmUrl(
    brandKit.websiteUrl || 'dsssbpyq.online',
    {
      source: utmSource,
      medium: utmMedium,
      campaign: utmCampaign,
      contentId: utmContent,
    }
  );

  const handleCopyUtm = () => {
    navigator.clipboard.writeText(generatedUtmUrl);
    setCopiedUtm(true);
    setTimeout(() => setCopiedUtm(false), 2000);
  };

  const handleOpenEditPack = (p: GeneratedContentPack) => {
    setSelectedPackForEdit(p);
    setLogViews(p.views || 0);
    setLogLikes(p.likes || 0);
    setLogComments(p.comments || 0);
    setLogShares(p.shares || 0);
    setLogSaves(p.saves || 0);
    setLogFollowers(p.followersGained || 0);
    setLogClicks(p.clicks || 0);
    setLogInstalls(p.appInstalls || 0);
    setLogPostUrl(p.postUrl || '');
  };

  const handleSaveMetrics = async () => {
    if (!selectedPackForEdit) return;
    await ConversionTrackingService.logPerformance(selectedPackForEdit.id, {
      views: logViews,
      likes: logLikes,
      comments: logComments,
      shares: logShares,
      saves: logSaves,
      followersGained: logFollowers,
      clicks: logClicks,
      appInstalls: logInstalls,
      postUrl: logPostUrl,
    });

    const refreshed = await IndexedDbService.getAllContentPacks();
    setPacks(refreshed);
    setSelectedPackForEdit(null);
  };

  return (
    <div className="max-w-6xl mx-auto px-4 py-8 space-y-8">
      {/* Header */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div className="space-y-1">
          <div className="flex items-center gap-2">
            {onBack && (
              <button
                onClick={onBack}
                className="p-1.5 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded-lg cursor-pointer transition-colors"
              >
                <ArrowLeft className="w-4 h-4" />
              </button>
            )}
            <span className="px-2.5 py-0.5 bg-emerald-500/20 text-emerald-400 border border-emerald-500/30 rounded-full text-xs font-black uppercase tracking-wide flex items-center gap-1.5">
              <TrendingUp className="w-3.5 h-3.5" />
              <span>BYTEPREP CONVERSION & ROI TRACKER</span>
            </span>
          </div>
          <h1 className="text-2xl sm:text-3xl font-black text-white">
            Social Conversion & Attribution Dashboard
          </h1>
          <p className="text-slate-400 text-xs sm:text-sm">
            Track views, link clicks, website visits, and Google Play Store downloads generated by your content.
          </p>
        </div>
      </div>

      {/* Aggregate Overview Metrics */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
        <div className="bg-slate-900/90 border border-slate-800 rounded-2xl p-4 space-y-1">
          <div className="text-[11px] font-bold text-slate-400 uppercase flex items-center gap-1.5">
            <Eye className="w-3.5 h-3.5 text-sky-400" />
            <span>Total Views</span>
          </div>
          <div className="text-2xl font-black text-white">
            {metrics.totalViews.toLocaleString()}
          </div>
        </div>

        <div className="bg-slate-900/90 border border-slate-800 rounded-2xl p-4 space-y-1">
          <div className="text-[11px] font-bold text-slate-400 uppercase flex items-center gap-1.5">
            <MousePointer className="w-3.5 h-3.5 text-amber-400" />
            <span>Website / CTA Clicks</span>
          </div>
          <div className="text-2xl font-black text-amber-400">
            {metrics.totalClicks.toLocaleString()}
          </div>
        </div>

        <div className="bg-slate-900/90 border border-slate-800 rounded-2xl p-4 space-y-1">
          <div className="text-[11px] font-bold text-slate-400 uppercase flex items-center gap-1.5">
            <UserPlus className="w-3.5 h-3.5 text-emerald-400" />
            <span>Followers Gained</span>
          </div>
          <div className="text-2xl font-black text-emerald-400">
            +{metrics.totalFollowersGained.toLocaleString()}
          </div>
        </div>

        <div className="bg-slate-900/90 border border-slate-800 rounded-2xl p-4 space-y-1">
          <div className="text-[11px] font-bold text-slate-400 uppercase flex items-center gap-1.5">
            <Download className="w-3.5 h-3.5 text-purple-400" />
            <span>Estimated App Installs</span>
          </div>
          <div className="text-2xl font-black text-purple-400">
            {metrics.totalAppInstalls.toLocaleString()}
          </div>
        </div>
      </div>

      {/* UTM Parameter Generator Tool */}
      <div className="bg-slate-900/90 border border-slate-800 rounded-3xl p-6 space-y-4 shadow-xl">
        <div className="flex items-center gap-2">
          <Link className="w-4 h-4 text-sky-400" />
          <h2 className="text-sm font-black text-white uppercase tracking-wider">
            Smart UTM Campaign Link Builder
          </h2>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-4 gap-3 text-xs">
          <div>
            <label className="text-slate-400 font-bold mb-1 block">Platform (utm_source)</label>
            <select
              value={utmSource}
              onChange={e => setUtmSource(e.target.value)}
              className="w-full bg-slate-950 border border-slate-700 rounded-xl px-3 py-2 text-white font-medium"
            >
              <option value="instagram">Instagram</option>
              <option value="youtube">YouTube</option>
              <option value="telegram">Telegram</option>
              <option value="whatsapp">WhatsApp</option>
              <option value="facebook">Facebook</option>
            </select>
          </div>

          <div>
            <label className="text-slate-400 font-bold mb-1 block">Medium (utm_medium)</label>
            <select
              value={utmMedium}
              onChange={e => setUtmMedium(e.target.value)}
              className="w-full bg-slate-950 border border-slate-700 rounded-xl px-3 py-2 text-white font-medium"
            >
              <option value="reel">Reels / Shorts</option>
              <option value="story">Story</option>
              <option value="carousel">Carousel</option>
              <option value="poll">Quiz Poll</option>
              <option value="bio_link">Bio Link</option>
            </select>
          </div>

          <div>
            <label className="text-slate-400 font-bold mb-1 block">Campaign (utm_campaign)</label>
            <input
              type="text"
              value={utmCampaign}
              onChange={e => setUtmCampaign(e.target.value)}
              className="w-full bg-slate-950 border border-slate-700 rounded-xl px-3 py-2 text-white font-medium"
            />
          </div>

          <div>
            <label className="text-slate-400 font-bold mb-1 block">Content ID (utm_content)</label>
            <input
              type="text"
              value={utmContent}
              onChange={e => setUtmContent(e.target.value)}
              className="w-full bg-slate-950 border border-slate-700 rounded-xl px-3 py-2 text-white font-medium font-mono"
            />
          </div>
        </div>

        {/* Generated Link Display */}
        <div className="flex items-center gap-2 bg-slate-950 p-3 rounded-2xl border border-slate-800 font-mono text-xs text-sky-300 overflow-x-auto">
          <span className="truncate flex-1">{generatedUtmUrl}</span>
          <button
            onClick={handleCopyUtm}
            className="flex items-center gap-1 px-3 py-1.5 bg-sky-500 hover:bg-sky-400 text-slate-950 font-black text-xs rounded-xl shrink-0 transition-colors cursor-pointer"
          >
            {copiedUtm ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
            <span>{copiedUtm ? 'Copied!' : 'Copy Link'}</span>
          </button>
        </div>
      </div>

      {/* Content Items & Performance Log Table */}
      <div className="bg-slate-900/90 border border-slate-800 rounded-3xl p-6 space-y-4">
        <h2 className="text-sm font-black text-white uppercase tracking-wider">
          Individual Content Item Attribution Log ({packs.length})
        </h2>

        <div className="space-y-2">
          {packs.map(p => (
            <div
              key={p.id}
              className="bg-slate-950 p-4 rounded-2xl border border-slate-800 hover:border-slate-700 transition-all flex flex-col sm:flex-row sm:items-center justify-between gap-4"
            >
              <div className="space-y-1 max-w-lg">
                <div className="flex items-center gap-2">
                  <span className="px-2 py-0.5 bg-slate-800 text-sky-400 rounded-md text-[10px] font-mono font-bold">
                    {p.contentId || p.id.slice(0, 16)}
                  </span>
                  <span className="text-[10px] font-bold text-slate-400">
                    {p.question.subject} • {p.question.topic}
                  </span>
                </div>
                <p className="text-xs font-bold text-white line-clamp-1">
                  {p.hook || p.question.question}
                </p>
              </div>

              {/* Metrics Pill */}
              <div className="flex items-center gap-3 text-xs font-semibold text-slate-300">
                <div className="text-center">
                  <div className="text-white font-bold">{p.views || 0}</div>
                  <div className="text-[9px] text-slate-500 uppercase">Views</div>
                </div>
                <div className="text-center">
                  <div className="text-amber-400 font-bold">{p.clicks || 0}</div>
                  <div className="text-[9px] text-slate-500 uppercase">Clicks</div>
                </div>
                <div className="text-center">
                  <div className="text-emerald-400 font-bold">+{p.followersGained || 0}</div>
                  <div className="text-[9px] text-slate-500 uppercase">Followers</div>
                </div>

                <button
                  onClick={() => handleOpenEditPack(p)}
                  className="px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-bold rounded-xl border border-slate-700 transition-colors cursor-pointer"
                >
                  Log Metrics
                </button>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Manual Metric Entry Modal */}
      {selectedPackForEdit && (
        <div className="fixed inset-0 z-50 bg-slate-950/80 backdrop-blur-sm flex items-center justify-center p-4">
          <div className="bg-slate-900 border border-slate-800 rounded-3xl p-6 max-w-md w-full space-y-4 shadow-2xl animate-fade-in">
            <h3 className="text-base font-black text-white">
              Log Real-World Performance
            </h3>
            <p className="text-xs text-slate-400 font-mono">
              ID: {selectedPackForEdit.contentId || selectedPackForEdit.id}
            </p>

            <div className="grid grid-cols-2 gap-3 text-xs">
              <div>
                <label className="text-slate-400 font-bold mb-1 block">Views</label>
                <input
                  type="number"
                  value={logViews}
                  onChange={e => setLogViews(parseInt(e.target.value, 10) || 0)}
                  className="w-full bg-slate-950 border border-slate-700 rounded-xl px-3 py-2 text-white font-medium"
                />
              </div>

              <div>
                <label className="text-slate-400 font-bold mb-1 block">Likes</label>
                <input
                  type="number"
                  value={logLikes}
                  onChange={e => setLogLikes(parseInt(e.target.value, 10) || 0)}
                  className="w-full bg-slate-950 border border-slate-700 rounded-xl px-3 py-2 text-white font-medium"
                />
              </div>

              <div>
                <label className="text-slate-400 font-bold mb-1 block">Comments</label>
                <input
                  type="number"
                  value={logComments}
                  onChange={e => setLogComments(parseInt(e.target.value, 10) || 0)}
                  className="w-full bg-slate-950 border border-slate-700 rounded-xl px-3 py-2 text-white font-medium"
                />
              </div>

              <div>
                <label className="text-slate-400 font-bold mb-1 block">Shares / Saves</label>
                <input
                  type="number"
                  value={logShares}
                  onChange={e => setLogShares(parseInt(e.target.value, 10) || 0)}
                  className="w-full bg-slate-950 border border-slate-700 rounded-xl px-3 py-2 text-white font-medium"
                />
              </div>

              <div>
                <label className="text-slate-400 font-bold mb-1 block">Followers Gained</label>
                <input
                  type="number"
                  value={logFollowers}
                  onChange={e => setLogFollowers(parseInt(e.target.value, 10) || 0)}
                  className="w-full bg-slate-950 border border-slate-700 rounded-xl px-3 py-2 text-white font-medium"
                />
              </div>

              <div>
                <label className="text-slate-400 font-bold mb-1 block">Link Clicks</label>
                <input
                  type="number"
                  value={logClicks}
                  onChange={e => setLogClicks(parseInt(e.target.value, 10) || 0)}
                  className="w-full bg-slate-950 border border-slate-700 rounded-xl px-3 py-2 text-white font-medium"
                />
              </div>
            </div>

            <div>
              <label className="text-slate-400 font-bold mb-1 block text-xs">Live Post URL</label>
              <input
                type="text"
                placeholder="https://instagram.com/reel/..."
                value={logPostUrl}
                onChange={e => setLogPostUrl(e.target.value)}
                className="w-full bg-slate-950 border border-slate-700 rounded-xl px-3 py-2 text-white font-medium text-xs"
              />
            </div>

            <div className="flex items-center justify-end gap-3 pt-3 border-t border-slate-800">
              <button
                onClick={() => setSelectedPackForEdit(null)}
                className="px-4 py-2 bg-slate-800 text-slate-300 font-bold text-xs rounded-xl hover:bg-slate-700 cursor-pointer"
              >
                Cancel
              </button>
              <button
                onClick={handleSaveMetrics}
                className="px-5 py-2 bg-emerald-500 hover:bg-emerald-400 text-slate-950 font-black text-xs rounded-xl shadow-lg cursor-pointer"
              >
                Save Metrics
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
